# Generated by Django 2.2.13 on 2020-12-13 18:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0037_auto_20201207_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Valid variable name', max_length=79, unique=True)),
                ('word', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Valid variable name', max_length=79, unique=True)),
                ('expression', models.TextField(help_text='Python expression returning a boolean.')),
                ('community', models.ManyToManyField(blank=True, help_text='This filter will be applied to these communities.', to='community.Community')),
                ('word', models.ManyToManyField(blank=True, help_text='Word objects used in the expression.', to='filter.Word')),
            ],
        ),
    ]
