# Generated by Django 2.2.13 on 2020-12-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this filter activated?'),
        ),
    ]
