# Generated by Django 2.1 on 2018-08-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpttest', '0004_auto_20180807_0400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statusdj',
            new_name='Treedj',
        ),
    ]
