# Generated by Django 2.2.4 on 2019-11-02 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation', '0037_auto_20191101_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptIn',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('identity', models.UUIDField()),
                ('version_start_date', models.DateTimeField()),
                ('version_end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('version_birth_date', models.DateTimeField()),
                ('authorize', models.BooleanField(default=None)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optin', to='optin.Option')),
                ('socialuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optin', to='moderation.SocialUser')),
            ],
            options={
                'abstract': False,
                'unique_together': {('id', 'identity')},
            },
        ),
    ]
