# Generated by Django 2.2.9 on 2019-12-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='default_bool',
            field=models.BooleanField(null=True),
        ),
    ]
