version: '3'

services:
          
  database:
    restart: always                                                                       
    image: postgres:10.10                                                        
    volumes:                                                                    
      - "${DATABASE_DATA_DIR}:/var/lib/postgresql/data" 
  redis:
    restart: always
    image: redis:latest
    sysctls:
      net.core.somaxconn: 1024
  celery_retweet_worker:
    restart: always
    env_file:
      - .env
    image: django:doctocnet
    command: bash -c "celery --app=${CELERY_APP} worker -Q retweet --concurrency=2 -n retweet_worker@%n --loglevel=${CELERYD_LOG_LEVEL} --logfile=${CELERYD_LOG_FILE}"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
    depends_on:
      - redis
    working_dir: /code/src
  celery_tree_worker:
    restart: always
    env_file:
      - .env
    image: django:doctocnet
    command: bash -c "celery --app=${CELERY_APP} worker -Q tree --concurrency=2 -n tree_worker@%n --loglevel=${CELERYD_LOG_LEVEL} --logfile=${CELERYD_LOG_FILE} --time-limit=${CELERY_TREE_SOFT_TIME_LIMIT}"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
    depends_on:
      - redis
    links:
      - redis
    working_dir: /code/src
  celery_celery_worker:
    restart: always
    env_file:
      - .env
    image: django:doctocnet
    command: bash -c "celery --app=${CELERY_APP} worker -Q celery --concurrency=2 -n celery_worker@%n --loglevel=${CELERYD_LOG_LEVEL} --logfile=${CELERYD_LOG_FILE}"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
    depends_on:
      - redis
    links:
      - redis
    working_dir: /code/src
  celery-beat:
    restart: always
    env_file:
      - .env
    image: django:doctocnet
    command: celery -A ${PROJECT} beat -l debug --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile=
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
    depends_on:
      - database
      - redis
      - celery_retweet_worker
      - celery_tree_worker
      - celery_celery_worker
    working_dir: /code/src
  stream:
    restart: always
    env_file:
      - .env
    image: django:doctocnet
    command: bash -c "python manage.py run_bot_stream --settings=settings"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
    depends_on:
      - redis
      - database
      - celery_retweet_worker
    working_dir: /code/src