services:
  django_1:
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      target: dev
    image: dtn_dev
    command: bash -c "DJANGO_SETTINGS_MODULE=doctocnet.settings python manage.py collectstatic --noinput && gunicorn doctocnet.wsgi:application --workers=${GUNICORN_WORKERS} --log-file=${GUNICORN_LOG}/gunicorn.log --log-level=${GUNICORN_LOG_LEVEL} -b '[::]:80' --worker-tmp-dir /dev/shm --timeout ${GUNICORN_TIMEOUT} --reload"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${GUNICORN_LOG}:${GUNICORN_LOG}
      - ${GNUPGHOME}:${GNUPGHOME}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    ports:
      - "8091:80"
    depends_on:
      - database
      - redis
    working_dir: /code/src
  django_2:
    restart: always
    env_file:
      - .env
    image: dtn_dev
    command: bash -c "DJANGO_SETTINGS_MODULE=doctocnet.settings2 gunicorn doctocnet.wsgi:application --workers=${GUNICORN_WORKERS} --log-file=${GUNICORN_LOG}/gunicorn.log --log-level=${GUNICORN_LOG_LEVEL} -b '[::]:80' --worker-tmp-dir /dev/shm --timeout ${GUNICORN_TIMEOUT} --reload"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${GUNICORN_LOG}:${GUNICORN_LOG}
      - ${GNUPGHOME}:${GNUPGHOME}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    ports:
      - "8092:80"
    depends_on:
      - database
      - redis
    working_dir: /code/src
  django_3:
    restart: always
    env_file:
      - .env
    image: dtn_dev
    command: bash -c "DJANGO_SETTINGS_MODULE=doctocnet.settings3 gunicorn doctocnet.wsgi:application --workers=${GUNICORN_WORKERS} --log-file=${GUNICORN_LOG}/gunicorn.log --log-level=${GUNICORN_LOG_LEVEL} -b '[::]:80' --worker-tmp-dir /dev/shm --timeout ${GUNICORN_TIMEOUT} --reload"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${GUNICORN_LOG}:${GUNICORN_LOG}
      - ${GNUPGHOME}:${GNUPGHOME}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    ports:
      - "8093:80"
    depends_on:
      - database
      - redis
    working_dir: /code/src
    profiles: ["full"]
  django_4:
    restart: always
    env_file:
      - .env
    image: dtn_dev
    command: bash -c "DJANGO_SETTINGS_MODULE=doctocnet.settings4 gunicorn doctocnet.wsgi:application --workers=${GUNICORN_WORKERS} --log-file=${GUNICORN_LOG}/gunicorn.log --log-level=${GUNICORN_LOG_LEVEL} -b '[::]:80' --worker-tmp-dir /dev/shm --timeout ${GUNICORN_TIMEOUT} --reload"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${GUNICORN_LOG}:${GUNICORN_LOG}
      - ${GNUPGHOME}:${GNUPGHOME}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    ports:
      - "8094:80"
    depends_on:
      - database
      - redis
    working_dir: /code/src
    profiles: ["full"]
  celery_retweet_worker:
    image: dtn_dev
    profiles: ["celery"]
  celery_tree_worker:
    image: dtn_dev
    profiles: ["celery"]
  celery_worker:
    image: dtn_dev
    profiles: ["celery"]
  celery-beat:
    image: dtn_dev
    profiles: ["celery"]
  flower:
    image: dtn_dev
    profiles: ["celery"]
  twitter_stream_1:
    image: dtn_dev
    restart: on-failure
    profiles: ["stream"]
  twitter_stream_2:
    image: dtn_dev
    restart: on-failure
    profiles: ["stream"]
  twitter_stream_3:
    image: dtn_dev
    restart: on-failure
    profiles: ["stream"]
  twitter_stream_4:
    image: dtn_dev
    restart: on-failure
    profiles: ["stream"]
  twitter_stream_5:
    image: dtn_dev
    restart: on-failure
    profiles: ["stream"]
  twitter_stream_6:
    image: dtn_dev
    restart: on-failure
    profiles: ["stream"]
  twitter_stream_7:
    image: dtn_dev
    restart: on-failure
    profiles: ["stream"]
  tree_search:
    image: dtn_dev
    restart: on-failure
    profiles: ["tree_search"]
  mastodon_stream_1:
    image: dtn_dev
    restart: on-failure
    profiles: ["stream"]
  mastodon_stream_2:
    image: dtn_dev
    restart: on-failure
    profiles: ["stream"]
  mastodon_stream_3:
    image: dtn_dev
    restart: on-failure
    profiles: ["stream"]
  mastodon_stream_4:
    image: dtn_dev
    restart: on-failure
    profiles: ["stream"]
  mastodon_stream_5:
    image: dtn_dev
    restart: on-failure
    profiles: ["stream"]
  mastodon_stream_6:
    image: dtn_dev
    restart: on-failure
    profiles: ["stream"]
  mastodon_stream_7:
    image: dtn_dev
    restart: on-failure
    profiles: ["stream"]
