version: '3.8'

services:
          
  database:
    restart: always                                                                       
    image: postgis/postgis:14-3.3
    shm_size: ${DATABASE_SHM_SIZE}
    command: >
      postgres
      -c config_file=/etc/postgresql.conf
      -c logging_collector=on
      -c log_directory=/var/log/postgresql
      -c log_min_duration_statement=${DATABASE_LOG_MIN_DURATION_STATEMENT}
      -c shared_buffers=${DATABASE_SHARED_BUFFERS}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:                                                                    
      - "${DATABASE_DATA_DIR}:/var/lib/postgresql/data"
      - "${DATABASE_CONF_FILE}:/etc/postgresql.conf"
      - "${DATABASE_BACKUP_DIR}:/backup"
      - "${DATABASE_LOG_DIR}:/var/log/postgresql"
  redis:
    restart: always
    image: redis:latest
    sysctls:
      net.core.somaxconn: 1024
  celery_retweet_worker:
    restart: always
    env_file:
      - .env
    command: bash -c "celery --app=${CELERY_APP} worker -Q retweet --hostname=retweet@%h --concurrency=${CELERY_RETWEET_CONCURRENCY} -n retweet_worker@%n --loglevel=${CELERYD_LOG_LEVEL} --logfile=${CELERYD_LOG_FILE}"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - redis
    working_dir: /code/src
  celery_tree_worker:
    restart: always
    env_file:
      - .env
    command: bash -c "celery --app=${CELERY_APP} worker -Q tree --hostname=tree@%h --concurrency=${CELERY_TREE_CONCURRENCY} -n tree_worker@%n --loglevel=${CELERYD_LOG_LEVEL} --logfile=${CELERYD_LOG_FILE} --time-limit=${CELERY_TREE_TIME_LIMIT}"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - redis
    links:
      - redis
    working_dir: /code/src
  celery_celery_worker:
    restart: always
    env_file:
      - .env
    command: bash -c "celery --app=${CELERY_APP} worker -Q celery --hostname=celery@%h --autoscale=${CELERY_MAX_CONCURRENCY},${CELERY_MIN_CONCURRENCY} -n celery_worker@%n --loglevel=${CELERYD_LOG_LEVEL} --logfile=${CELERYD_LOG_FILE}"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - redis
    links:
      - redis
    working_dir: /code/src
  celery-beat:
    restart: always
    env_file:
      - .env
    command: celery -A ${PROJECT} beat -l debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - database
      - redis
      - celery_retweet_worker
      - celery_tree_worker
      - celery_celery_worker
    working_dir: /code/src
  flower:
    restart: always
    env_file:
      - .env
    command: celery -A ${PROJECT} flower --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}
    environment:
      - CELERY_BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
      - FLOWER_PORT=8888
    ports:  
      - 8888:8888
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - redis
    working_dir: /code/src
  mastodon_stream_1:
    env_file:
      - .env
    command: bash -c "python manage.py multi_hashtag_stream ${MASTODON_STREAM_1} --settings=settings"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - redis
      - database
      - celery_retweet_worker
    working_dir: /code/src
  mastodon_stream_2:
    env_file:
      - .env
    command: bash -c "python manage.py multi_hashtag_stream ${MASTODON_STREAM_2} --settings=settings"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - redis
      - database
      - celery_retweet_worker
    working_dir: /code/src
  mastodon_stream_3:
    env_file:
      - .env
    command: bash -c "python manage.py multi_hashtag_stream ${MASTODON_STREAM_3} --settings=settings"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - redis
      - database
      - celery_retweet_worker
    working_dir: /code/src
  mastodon_stream_4:
    env_file:
      - .env
    command: bash -c "python manage.py multi_hashtag_stream ${MASTODON_STREAM_4} --settings=settings"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - redis
      - database
      - celery_retweet_worker
    working_dir: /code/src
  mastodon_stream_5:
    env_file:
      - .env
    command: bash -c "python manage.py multi_hashtag_stream ${MASTODON_STREAM_5} --settings=settings"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - redis
      - database
      - celery_retweet_worker
    working_dir: /code/src
  mastodon_stream_6:
    env_file:
      - .env
    command: bash -c "python manage.py multi_hashtag_stream ${MASTODON_STREAM_6} --settings=settings"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - redis
      - database
      - celery_retweet_worker
    working_dir: /code/src
  mastodon_stream_7:
    env_file:
      - .env
    command: bash -c "python manage.py multi_hashtag_stream ${MASTODON_STREAM_7} --settings=settings"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${celery_base_dir}:${celery_base_dir}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - redis
      - database
      - celery_retweet_worker
    working_dir: /code/src