version: '3.8'

services:
  django_1:
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      target: prod
    image: dtn_prod
    command: bash -c "DJANGO_SETTINGS_MODULE=doctocnet.settings python manage.py rename_app mastodon fediverse && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn doctocnet.wsgi:application --workers=${GUNICORN_WORKERS} --log-file=${GUNICORN_LOG}/gunicorn.log --log-level=${GUNICORN_LOG_LEVEL} -b '[::]:80' --worker-tmp-dir /dev/shm --timeout ${GUNICORN_TIMEOUT}"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${GUNICORN_LOG}:${GUNICORN_LOG}
      - ${GNUPGHOME}:${GNUPGHOME}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - database
      - redis
    working_dir: /code/src
    ports:
      - "${PORT_GUNICORN_1}:80"
  django_2:
    restart: always
    env_file:
      - .env
    image: dtn_prod
    command: bash -c "DJANGO_SETTINGS_MODULE=doctocnet.settings2 gunicorn doctocnet.wsgi:application --workers=${GUNICORN_WORKERS} --log-file=${GUNICORN_LOG}/gunicorn.log --log-level=${GUNICORN_LOG_LEVEL} -b '[::]:80' --worker-tmp-dir /dev/shm --timeout ${GUNICORN_TIMEOUT} --reload"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${GUNICORN_LOG}:${GUNICORN_LOG}
      - ${GNUPGHOME}:${GNUPGHOME}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - database
      - redis
    working_dir: /code/src
    ports:
      - "${PORT_GUNICORN_2}:80"
    profiles: ["full"]
  django_3:
    restart: always
    env_file:
      - .env
    image: dtn_prod
    command: bash -c "DJANGO_SETTINGS_MODULE=doctocnet.settings3 gunicorn doctocnet.wsgi:application --workers=${GUNICORN_WORKERS} --log-file=${GUNICORN_LOG}/gunicorn.log --log-level=${GUNICORN_LOG_LEVEL} -b '[::]:80' --worker-tmp-dir /dev/shm --timeout ${GUNICORN_TIMEOUT} --reload"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${GUNICORN_LOG}:${GUNICORN_LOG}
      - ${GNUPGHOME}:${GNUPGHOME}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - database
      - redis
    working_dir: /code/src
    ports:
      - "${PORT_GUNICORN_3}:80"
    profiles: ["full"]
  django_4:
    restart: always
    env_file:
      - .env
    image: dtn_prod
    command: bash -c "DJANGO_SETTINGS_MODULE=doctocnet.settings4 gunicorn doctocnet.wsgi:application --workers=${GUNICORN_WORKERS} --log-file=${GUNICORN_LOG}/gunicorn.log --log-level=${GUNICORN_LOG_LEVEL} -b '[::]:80' --worker-tmp-dir /dev/shm --timeout ${GUNICORN_TIMEOUT} --reload"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${GUNICORN_LOG}:${GUNICORN_LOG}
      - ${GNUPGHOME}:${GNUPGHOME}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - database
      - redis
    working_dir: /code/src
    ports:
      - "${PORT_GUNICORN_4}:80"
    profiles: ["full"]
  django_5:
    restart: always
    env_file:
      - .env
    image: dtn_prod
    command: bash -c "DJANGO_SETTINGS_MODULE=doctocnet.settings5 gunicorn doctocnet.wsgi:application --workers=${GUNICORN_WORKERS} --log-file=${GUNICORN_LOG}/gunicorn.log --log-level=${GUNICORN_LOG_LEVEL} -b '[::]:80' --worker-tmp-dir /dev/shm --timeout ${GUNICORN_TIMEOUT} --reload"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${GUNICORN_LOG}:${GUNICORN_LOG}
      - ${GNUPGHOME}:${GNUPGHOME}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - database
      - redis
    working_dir: /code/src
    ports:
      - "8085:80"
    profiles: ["full"]
  django_6:
    restart: always
    env_file:
      - .env
    image: dtn_prod
    command: bash -c "DJANGO_SETTINGS_MODULE=doctocnet.settings6 gunicorn doctocnet.wsgi:application --workers=${GUNICORN_WORKERS} --log-file=${GUNICORN_LOG}/gunicorn.log --log-level=${GUNICORN_LOG_LEVEL} -b '[::]:80' --worker-tmp-dir /dev/shm --timeout ${GUNICORN_TIMEOUT} --reload"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${GUNICORN_LOG}:${GUNICORN_LOG}
      - ${GNUPGHOME}:${GNUPGHOME}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - database
      - redis
    working_dir: /code/src
    ports:
      - "${PORT_GUNICORN_6}:80"
    profiles: ["full"]
  django_7:
    restart: always
    env_file:
      - .env
    image: dtn_prod
    command: bash -c "DJANGO_SETTINGS_MODULE=doctocnet.settings7 gunicorn doctocnet.wsgi:application --workers=${GUNICORN_WORKERS} --log-file=${GUNICORN_LOG}/gunicorn.log --log-level=${GUNICORN_LOG_LEVEL} -b '[::]:80' --worker-tmp-dir /dev/shm --timeout ${GUNICORN_TIMEOUT} --reload"
    volumes:
      - ./src:/code/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${BOT_IMAGES_PATH}:${BOT_IMAGES_PATH}
      - ${GUNICORN_LOG}:${GUNICORN_LOG}
      - ${GNUPGHOME}:${GNUPGHOME}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    depends_on:
      - database
      - redis
    working_dir: /code/src
    ports:
      - "${PORT_GUNICORN_7}:80"
    profiles: ["full"]
  mastodon_stream_1:
    image: dtn_prod
    restart: on-failure:3
  mastodon_stream_2:
    image: dtn_prod
    restart: on-failure:3
  mastodon_stream_3:
    image: dtn_prod
    restart: on-failure:3
  mastodon_stream_4:
    image: dtn_prod
    restart: on-failure:3
  mastodon_stream_5:
    image: dtn_prod
    restart: on-failure:3
  mastodon_stream_6:
    image: dtn_prod
    restart: on-failure:3
  mastodon_stream_7:
    image: dtn_prod
    restart: on-failure:3