# Generated by Django 3.2.13 on 2022-06-03 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation', '0082_remove_socialuser_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Is this Twitter SocialUser active? For Twitter, not active means deactivated or deleted.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('socialuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active', to='moderation.socialuser')),
            ],
        ),
    ]
