"""
Django settings for doctocnet project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from django.utils.translation import gettext_lazy as _
import os
import logging
from django.utils.log import DEFAULT_LOGGING
from decouple import AutoConfig, Csv
from pathlib import Path

mpl_logger = logging.getLogger('matplotlib')
mpl_logger.setLevel(logging.WARNING) 

logger = logging.getLogger(__name__)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

CONFIG_DIR = Path(BASE_DIR + "/..")
config = AutoConfig(search_path = CONFIG_DIR)

LOG_LEVEL = config('LOG_LEVEL', default='DEBUG')

DICT_CONFIG = {
    "version": 1,
    "disable_existing_loggers": False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    "formatters": {
        "default": {
            "format": "%(asctime)s %(name)s %(pathname)s:%(lineno)s:%(funcName)s %(levelname)s %(message)s",
        },
        "django.server": DEFAULT_LOGGING['formatters']['django.server'],
    },

    "handlers": {
        'console': {
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'default',
            'filters': ['require_debug_true'],
    },

        "console_debug_false": {
            "level": LOG_LEVEL,
            "filters": ["require_debug_false"],
            "class": "logging.StreamHandler",
        },

        "mail_admins": {
            "level": "ERROR",
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler"
        },
        
        "django.server": DEFAULT_LOGGING["handlers"]["django.server"],

    },

    "loggers": {
        '': {
            'level': LOG_LEVEL,
            'handlers': ['console'],
            'propagate': False,
        },
        "django": {
            "handlers": ["console", "console_debug_false", "mail_admins"],
            "level": LOG_LEVEL,
        },
        "bot.stream": {
            "handlers": ["console", "console_debug_false", "mail_admins"],
            "level": LOG_LEVEL,
        },
        "bot.tasks": {
            "handlers": ["console", "console_debug_false", "mail_admins"],
            "level": LOG_LEVEL,
        },
        "messenger.tasks": {
            "handlers": ["console", "console_debug_false", "mail_admins"],
            "level": LOG_LEVEL,
        },
        "django.server": DEFAULT_LOGGING["loggers"]["django.server"],
    },
}
logging.config.dictConfig(DICT_CONFIG)

#sys.path.append(os.path.dirname(os.path.abspath(__file__)))



DEBUG = config('DEBUG', default=True, cast=bool)


SECRET_KEY = config('SECRET_KEY')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv(), default=['*'])

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SITE_ID = config('SITE_ID', cast=int, default=1)

# WAGTAIL
WAGTAIL_SITE_NAME = config('WAGTAIL_SITE_NAME')
WAGTAIL_FRONTEND_LOGIN_URL = '/accounts/login/'

# Application definition

INSTALLED_APPS = [
    'users',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'doctocnet',
    'landing',
    'social_django',
    'moderation',
    'conversation',
    'bot',
    'dm',
    'charts',
    'display',
    'timeline',
    'crispy_forms',
    'crowdfunding',
    'registration',
    'django_countries',
    'customer',
    'mptt',
    'dry_rest_permissions',
    #'corsheaders',
    'django_celery_beat',
    'messenger',
    'rangefilter',
    'dashboard',
# wagtail start
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.core',
    
    'modelcluster',
    'taggit',
# wagtail stop
# wagtail blog
    'blog',
    'meta',
    'wagtailmetadata',
    'ajax_select',
# wagtail blog stop
    'django.contrib.sites',
    'link',
    'gpgcontact',
]

MIDDLEWARE = [
    # CORS
    #'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
# wagtail start
    'wagtail.core.middleware.SiteMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
# wagtail stop
]

ROOT_URLCONF = 'doctocnet.urls'

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            'templates',     
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'django.template.context_processors.media',
                'django.template.context_processors.i18n',
                'doctocnet.context_processors.site',
            ],
        },
    },
]

WSGI_APPLICATION = 'doctocnet.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DATABASE_NAME', default='postgres'),
        'USER': config('DATABASE_USER', default='postgres'),
        'PASSWORD': config('DATABASE_PASSWORD', default=''),
        'HOST': config('DATABASE_HOST', default='database'),
        'PORT': config('DATABASE_PORT', cast=int, default=5432),
    }
}

STATIC_ROOT = config('STATIC_ROOT')
STATIC_URL = '/static/'

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'fr'


LANGUAGES = [
    ('fr', _('French')),
#    ('en', _('English')),

]

# use this locale to sort localized strings, default to 'en_US.UTF-8'
# you have to generate the locales you will use on your GNU/Linux server:
# $ locale-gen fr_FR.UTF-8
# $ locale-gen en_US.UTF-8
# To check the list of installed locales:
# $ locale -a

#SORTING_LOCALE = 'fr_FR.UTF-8'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True




LOGIN_URL = '/accounts/login/'
LOGOUT_URL = '/accounts/logout/'
LOGIN_REDIRECT_URL = '/user/'

# custom user model
AUTH_USER_MODEL = 'users.User'

# social auth
SOCIAL_AUTH_POSTGRES_JSONFIELD = True
SOCIAL_AUTH_LOGIN_ERROR_URL = '/settings/'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/user/'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False


AUTHENTICATION_BACKENDS = (
    'social_core.backends.twitter.TwitterOAuth',
    #'social_core.backends.github.GithubOAuth2',
    #'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)



SOCIAL_AUTH_TWITTER_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'moderation.profile.socialuser',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'moderation.profile.user',
    'moderation.profile.profile',
    'doctocnet.twitterinfo.show_profile',  # <--- set the path to the function
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)
MEDIA_ROOT = config('MEDIA_ROOT')
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'

# Redis & Celery
REDIS_HOST = config('REDIS_HOST', default='redis')
REDIS_PORT = config('REDIS_PORT', cast=str, default='6379')
CELERY_BROKER_URL = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,
    'fanout_prefix': True,
    'fanout_patterns': True} 
CELERY_RESULT_BACKEND = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
CELERY_TASK_SOFT_TIME_LIMIT = 1010
CELERY_TASK_TIME_LIMIT = 1020
CELERY_LOG_FILE = config('CELERY_LOG_FILE')

CELERY_TASK_ROUTES = {
    'bot.tasks.handle_on_status': {'queue': 'retweet'},
    'conversation.tasks.handle_update_trees': {'queue': 'tree'},
}

# CACHE
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://" + REDIS_HOST + ":" + REDIS_PORT + "/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
DISPLAY_CACHE=config('DISPLAY_CACHE', cast=int, default=60)

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

#Default time delta in hours for all functions related to scraping web tweets
SCRAPING_HOUR_DELTA = config('SCRAPING_HOUR_DELTA', cast=int)

# crispy_forms options
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# django-registration
ACCOUNT_ACTIVATION_DAYS = 7 # One-week activation window

MIGRATION_MODULES = {
    'sites': 'doctocnet.data_migrations.sites_migrations',
}

PAGINATION = config('PAGINATION', cast=int, default=1000)
DATA_UPLOAD_MAX_NUMBER_FIELDS = config('DATA_UPLOAD_MAX_NUMBER_FIELDS', cast=int, default=5000)

MODERATION = {
    "dev": False,
    "moderator": True
}

STATUS_DISPLAY_NUMBER = {
    'all': 10,
    'last': 10,
    'help': 10,
    'top': 10
}

STATUS_DISPLAY_HOUR = {
    'all': 48,
    'last': 48,
    'help': 48,
    'top': 48
}

BEAT_PERIOD = {
    'record_timeline': 60.0,
    'scrape_web_timeline': 120.0,
    'normalize': 600.0,
    'poll_dm': 600.0,
    'poll_moderation_dm': 600.0,
    'update_trees': 300.0,
    'poll_lists_members': 900.0,
}

MODERATION_AUTHORIZED_CATEGORIES = config('MODERATION_AUTHORIZED_CATEGORIES', cast=Csv())

#CORS_ORIGIN_ALLOW_ALL = True

# Messenger DM per task limit
MESSENGER_DM_LIMIT = 15

# django-meta
META_SITE_PROTOCOL = 'https'
META_USE_SITES = True
META_USE_TWITTER_PROPERTIES = True

# Stripe
STRIPE_PUBLIC_KEY = config("STRIPE_PUBLIC_KEY", default="")
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_LIVE_MODE = False

SERVER_EMAIL = config('SERVER_EMAIL', default='noreply@example.com')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@example.com')
ADMIN_FIRST_NAME = config('ADMIN_FIRST_NAME', default='admin')
ADMIN_LAST_NAME = config('ADMIN_LAST_NAME', default='admin')
ADMIN_NAME = " ".join([ADMIN_FIRST_NAME, ADMIN_LAST_NAME])
ADMIN_EMAIL_ADDRESS = config('ADMIN_EMAIL_ADDRESS', default='admin@example.com')
ADMINS=[
(ADMIN_NAME, ADMIN_EMAIL_ADDRESS),
]
MANAGERS=ADMINS
EMAIL_BACKEND=config('EMAIL_BACKEND')

# investment
PROJECT_NAME = 'doctoctocbot'

# django-registration
REGISTRATION_SALT = config('REGISTRATION_SALT')
ACCOUNT_ACTIVATION_DAYS = config('ACCOUNT_ACTIVATION_DAYS', default=1, cast=int)

import mimetypes
mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("text/css", ".scss", True)

# main bot Twitter account
TWITTER_CONSUMER_KEY = config('TWITTER_CONSUMER_KEY')
TWITTER_CONSUMER_SECRET = config('TWITTER_CONSUMER_SECRET')
TWITTER_ACCESS_TOKEN = config('TWITTER_ACCESS_TOKEN')
TWITTER_ACCESS_TOKEN_SECRET = config('TWITTER_ACCESS_TOKEN_SECRET')
BOT_IMAGES_PATH = config('BOT_IMAGES_PATH')
BOT_ID = config('BOT_ID', cast=int)
BOT_SCREEN_NAME = config('BOT_SCREEN_NAME')
KEYWORD_TRACK_LIST = config('KEYWORD_TRACK_LIST', cast=Csv())
KEYWORD_RETWEET_LIST = config('KEYWORD_RETWEET_LIST', cast=Csv())
NUMBER_OF_RT = 20
TWEET_LANGUAGE = ""

# backend bot Twitter API credentials (same as main credentials for dev)
BACKEND_TWITTER_CONSUMER_KEY = config('BACKEND_TWITTER_CONSUMER_KEY', default=TWITTER_CONSUMER_KEY)
BACKEND_TWITTER_CONSUMER_SECRET = config('BACKEND_TWITTER_CONSUMER_SECRET', default=TWITTER_CONSUMER_SECRET)
BACKEND_TWITTER_ACCESS_TOKEN = config('BACKEND_TWITTER_ACCESS_TOKEN', default=TWITTER_ACCESS_TOKEN)
BACKEND_TWITTER_ACCESS_TOKEN_SECRET = config('BACKEND_TWITTER_ACCESS_TOKEN_SECRET', default=TWITTER_ACCESS_TOKEN_SECRET)

# Twitter key (social-auth-app-django)
SOCIAL_AUTH_TWITTER_KEY = config('TWITTER_CONSUMER_KEY')
SOCIAL_AUTH_TWITTER_SECRET = config('TWITTER_CONSUMER_SECRET')

# gpgcontact
GNUPGHOME = config('GNUPGHOME')
GNUPG_PUBLIC_KEYS = config('GNUPG_PUBLIC_KEYS', cast=Csv())

PROFILE_TIMEDELTA_DAYS = config('PROFILE_TIMEDELTA_DAYS', default=0, cast=int)
FOLLOWER_TIMEDELTA_HOUR = config('FOLLOWER_TIMEDELTA_HOUR', default=24, cast=int)

TRANSLATION_OVERRIDE='fr'

# django-meta
META_SITE_PROTOCOL = 'http'

# Constants
# url used to fetch a status from its status id
TWITTER_STATUS_URL='https://twitter.com/i/web/status/{id}'