# Generated by Django 2.2.4 on 2019-09-02 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0002_auto_20190630_1321'),
        ('conversation', '0019_auto_20190804_0625'),
        ('moderation', '0021_auto_20190622_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=101, unique=True)),
                ('domain', models.CharField(help_text='Domain name', max_length=253, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('site', models.IntegerField(help_text='Site ID', unique=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.Account')),
                ('category', models.ManyToManyField(to='moderation.Category')),
                ('hashtag', models.ManyToManyField(to='conversation.Hashtag')),
            ],
            options={
                'verbose_name_plural': 'communities',
            },
        ),
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reweet', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.Category')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversation.Hashtag')),
            ],
            options={
                'unique_together': {('community', 'hashtag', 'category')},
            },
        ),
    ]
