# Generated by Django 2.2.6 on 2019-10-10 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
        ('crowdfunding', '0001_initial'),
        ('moderation', '0001_initial'),
        ('conversation', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=101, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.Account')),
                ('crowdfunding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='crowdfunding.Project')),
                ('hashtag', models.ManyToManyField(to='conversation.Hashtag')),
                ('membership', models.ManyToManyField(related_name='member_of', to='moderation.Category')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='community', to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'communities',
            },
        ),
    ]
