# Generated by Django 2.2.6 on 2019-10-10 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
        ('community', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityCategoryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickreply', models.BooleanField(default=False, help_text='Include in DM quickreply?')),
                ('socialgraph', models.BooleanField(default=False, help_text='Include in moderation social graph?')),
                ('color', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_relationship', to='moderation.Category')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_relationship', to='community.Community')),
            ],
            options={
                'unique_together': {('community', 'category')},
            },
        ),
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.ManyToManyField(related_name='community', through='community.CommunityCategoryRelationship', to='moderation.Category'),
        ),
    ]
