# Generated by Django 2.2.6 on 2019-10-10 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
        ('community', '0003_auto_20191010_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('authorized', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.Category')),
                ('from_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_from', to='community.Community')),
                ('to_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_to', to='community.Community')),
            ],
            options={
                'unique_together': {('from_community', 'to_community', 'category')},
            },
        ),
        migrations.AddField(
            model_name='community',
            name='trust',
            field=models.ManyToManyField(related_name='trusted_by', through='community.Trust', to='community.Community'),
        ),
    ]
