# Generated by Django 2.2.4 on 2019-09-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0026_auto_20190915_2314'),
        ('community', '0003_auto_20190909_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='category',
        ),
        migrations.AddField(
            model_name='community',
            name='membership',
            field=models.ManyToManyField(to='moderation.Category'),
        ),
    ]
