# Generated by Django 2.2.6 on 2019-10-10 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20191010_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('authorized', models.BooleanField(default=False)),
                ('from_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperation_from', to='community.Community')),
                ('to_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperation_to', to='community.Community')),
            ],
            options={
                'unique_together': {('from_community', 'to_community')},
            },
        ),
        migrations.AddField(
            model_name='community',
            name='cooperation',
            field=models.ManyToManyField(related_name='cooperating_with', through='community.Cooperation', to='community.Community'),
        ),
    ]
