# Generated by Django 2.2.4 on 2019-09-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
#        ('moderation', '0027_auto_20190918_0955'),
        ('community', '0004_auto_20190917_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='membership',
            field=models.ManyToManyField(related_name='member_of', to='moderation.Category'),
        ),
        migrations.CreateModel(
            name='CommunityCategoryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickreply', models.BooleanField(default=False, help_text='Include in DM quickreply?')),
                ('socialgraph', models.BooleanField(default=False, help_text='Include in moderation social graph?')),
                ('color', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_relationship', to='moderation.Category')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_relationship', to='community.Community')),
            ],
            options={
                'unique_together': {('community', 'category')},
            },
        ),
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.ManyToManyField(related_name='community', through='community.CommunityCategoryRelationship', to='moderation.Category'),
        ),
    ]
