# Generated by Django 2.2.4 on 2019-09-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20190918_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
