# Generated by Django 2.2.6 on 2019-10-10 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        ('moderation', '0001_initial'),
        ('community', '0005_auto_20191010_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retweet', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.Category')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversation.Hashtag')),
            ],
            options={
                'unique_together': {('community', 'hashtag', 'category')},
            },
        ),
    ]
