# Generated by Django 2.2.4 on 2019-10-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_retweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycategoryrelationship',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
