# Generated by Django 2.2.10 on 2020-03-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_community_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='helper_message',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
