# Generated by Django 2.2.4 on 2019-10-06 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_remove_community_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='community', to='sites.Site'),
        ),
    ]
