# Generated by Django 2.2.10 on 2020-03-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_retweet_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='helper_message',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
