# Generated by Django 2.2.10 on 2020-03-18 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_auto_20200318_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retweet',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moderation.Category'),
        ),
    ]
