# Generated by Django 2.2.10 on 2020-03-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_auto_20200318_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='allow_retweet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retweet',
            name='require_question',
            field=models.BooleanField(default=True),
        ),
    ]
