# Generated by Django 2.2.10 on 2020-03-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_auto_20200318_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='allow_unknown',
            field=models.BooleanField(default=False),
        ),
    ]
