# Generated by Django 2.2.10 on 2020-03-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_retweet_allow_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retweet',
            name='allow_unknown',
        ),
    ]
