# Generated by Django 2.2.10 on 2020-03-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_remove_retweet_allow_unknown'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='allow_unknown',
            field=models.BooleanField(default=False),
        ),
    ]
