# Generated by Django 2.2.10 on 2020-03-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_community_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='require_follower',
            field=models.BooleanField(default=True),
        ),
    ]
