# Generated by Django 2.2.10 on 2020-04-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_retweet_require_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='pending_moderation_period',
            field=models.PositiveIntegerField(default=0, help_text='Pending moderation period (hour)'),
        ),
    ]
