# Generated by Django 2.2.10 on 2020-04-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0052_auto_20200328_0231'),
        ('community', '0022_community_pending_moderation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='viral_moderation',
            field=models.BooleanField(default=False, help_text='Does a verified follower immediately become a moderator?'),
        ),
        migrations.AddField(
            model_name='community',
            name='viral_moderation_category',
            field=models.ManyToManyField(blank=True, related_name='viral_moderation_community', to='moderation.Category'),
        ),
    ]
