# Generated by Django 2.2.10 on 2020-04-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_auto_20200408_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='viral_moderation_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
