# Generated by Django 2.2.10 on 2020-04-15 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0024_community_viral_moderation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='sites.Site'),
        ),
    ]
