# Generated by Django 2.2.10 on 2020-05-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0025_auto_20200415_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='verification_threshold_follower',
            field=models.PositiveIntegerField(default=1, help_text='Start verification if follower count superior or equal to'),
        ),
    ]
