# Generated by Django 2.2.13 on 2020-06-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0056_human'),
        ('community', '0026_community_verification_threshold_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='follower',
            field=models.ManyToManyField(blank=True, help_text='Categories authorized to follow the account if protected', related_name='follower_of', to='moderation.Category'),
        ),
    ]
