# Generated by Django 2.2.13 on 2020-06-18 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0027_community_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('label', models.CharField(max_length=254)),
                ('label_fr', models.CharField(max_length=254, null=True)),
                ('label_en', models.CharField(max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='community.Community')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='community.TextDescription')),
            ],
            options={
                'unique_together': {('community', 'type')},
            },
        ),
    ]
