# Generated by Django 2.2.13 on 2020-08-08 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_account_phone'),
        ('community', '0030_community_request_queue_backoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='follower_common_account',
            field=models.ManyToManyField(help_text='These Accounts are part of a common follower community for retweeting purpose. If a user follows one of those accounts, she will be retweeted by the current Account.', related_name='follower_common_account_community', to='bot.Account'),
        ),
        migrations.AlterField(
            model_name='community',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community', to='bot.Account'),
        ),
    ]
