# Generated by Django 2.2.13 on 2020-10-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0031_auto_20200808_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('label', models.CharField(max_length=254)),
                ('label_fr', models.CharField(max_length=254, null=True)),
                ('label_en', models.CharField(max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
