# Generated by Django 2.2.13 on 2020-10-23 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0032_accesslevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_limit', models.IntegerField(blank=True, default=0, help_text='Total number of status.', null=True, verbose_name='Status limit')),
                ('status_rate', models.IntegerField(blank=True, default=0, help_text='Number of status per minute.', null=True, verbose_name='Status rate (per minute)')),
                ('author_category', models.BooleanField(default=False, help_text='Category of the author of the status.', verbose_name='Author category')),
                ('author_specialty', models.BooleanField(default=False, help_text='Specialty of the author of the status.', verbose_name='Author specialty')),
                ('search_datetime', models.BooleanField(default=False, help_text='Search status by date and time.', verbose_name='Date and Time search')),
                ('search_category', models.BooleanField(default=False, help_text='Search status by category.', verbose_name='Category search')),
                ('search_tag', models.BooleanField(default=False, help_text='Search status by tag.', verbose_name='Tag search')),
                ('status_category', models.BooleanField(default=False, help_text='Access status category.', verbose_name='Status category')),
                ('status_tag', models.BooleanField(default=False, help_text='Access status tag.', verbose_name='Status tag')),
                ('status_protected', models.BooleanField(default=False, help_text='Access status from protected account.', verbose_name='Protected status')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_access', to='community.Community')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_access', to='community.AccessLevel')),
            ],
            options={
                'unique_together': {('community', 'level')},
            },
        ),
    ]
