# Generated by Django 2.2.13 on 2020-11-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0033_apiaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccess',
            name='status_media',
            field=models.BooleanField(default=False, help_text='Access status media.', verbose_name='Status media'),
        ),
    ]
