# Generated by Django 2.2.13 on 2020-12-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0034_apiaccess_status_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='tree_search',
            field=models.BooleanField(default=False, help_text='Launch a conversation tree nodes search based on Twitter API for this community at startup'),
        ),
    ]
