# Generated by Django 2.2.13 on 2020-12-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0035_community_tree_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='no_root_backoff',
            field=models.PositiveIntegerField(blank=True, help_text='tree_search backoff period after no root found (second)', null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='tree_search_retry',
            field=models.PositiveIntegerField(blank=True, help_text='minimum retry period after all roots processed (second)', null=True),
        ),
    ]
