# Generated by Django 2.2.13 on 2020-12-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0036_auto_20201206_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='follower_common_account',
            field=models.ManyToManyField(blank=True, help_text='These Accounts are part of a common follower community for retweeting purpose. If a user follows one of those accounts, she will be retweeted by the current Account.', related_name='follower_common_account_community', to='bot.Account'),
        ),
    ]
