# Generated by Django 2.2.13 on 2021-01-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0038_community_twitter_follow_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccess',
            name='reply_count',
            field=models.BooleanField(default=False, help_text='Access status reply count.', verbose_name='Reply count'),
        ),
    ]
