# Generated by Django 2.2.17 on 2021-02-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0039_apiaccess_reply_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='twitter_request_dm',
            field=models.BooleanField(default=False, help_text='Twitter account will attempt to send a DM after a follow request.'),
        ),
        migrations.AddField(
            model_name='community',
            name='twitter_request_dm_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
