# Generated by Django 2.2.17 on 2021-04-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0041_auto_20210311_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='helper_message',
            field=models.TextField(blank=True, max_length=257, null=True),
        ),
    ]
