# Generated by Django 2.2.20 on 2021-04-12 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0042_auto_20210407_0507'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='text',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='TextCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Text')),
            ],
            options={
                'unique_together': {('text', 'community')},
            },
        ),
        migrations.RemoveField(
            model_name='text',
            name='community',
        ),
        migrations.AddField(
            model_name='text',
            name='community',
            field=models.ManyToManyField(related_name='text', through='community.TextCommunity', to='community.Community'),
        ),
    ]
