# Generated by Django 2.2.20 on 2021-04-15 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0043_auto_20210412_0636'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textcommunity',
            unique_together=set(),
        ),
    ]
