# Generated by Django 2.2.24 on 2021-09-16 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0047_communitycategoryrelationship_self'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitycategoryrelationship',
            old_name='self',
            new_name='quickreply_self',
        ),
    ]
