# Generated by Django 2.2.24 on 2021-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0048_auto_20210916_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
