# Generated by Django 2.2.24 on 2021-10-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0049_retweet_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='pending_moderation_period',
            field=models.IntegerField(
                blank=True,
                null=True
            ),
        ),
    ]
