# Generated by Django 2.2.24 on 2021-10-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0051_auto_20211015_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='pending_moderation_period',
        ),
    ]
