# Generated by Django 2.2.24 on 2021-10-15 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0052_remove_community_pending_moderation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='pending_moderation_period',
            field=models.DurationField(blank=True, default=datetime.timedelta, help_text='Duration before moderation sent to other moderator Format: [DD] [HH:[MM:]]ss[.uuuuuu]', null=True),
        ),
    ]
