# Generated by Django 2.2.24 on 2021-10-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0053_community_pending_moderation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycategoryrelationship',
            name='do_not_follow',
            field=models.BooleanField(default=False, help_text='Bot should not follow SocialUsers from this category'),
        ),
    ]
