# Generated by Django 2.2.24 on 2021-11-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0054_communitycategoryrelationship_do_not_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='sites.Site'),
        ),
    ]
