# Generated by Django 3.2.9 on 2021-11-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0012_projectinvestment_campaign'),
        ('community', '0056_auto_20211103_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='crowdfunding',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='crowdfunding.project'),
        ),
    ]
