# Generated by Django 3.2.9 on 2021-12-10 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0059_alter_blog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='pending_self_moderation_period',
            field=models.DurationField(blank=True, default=datetime.timedelta, help_text='Duration before self moderation sent again Format: [DD] [HH:[MM:]]ss[.uuuuuu]', null=True),
        ),
    ]
