# Generated by Django 3.2.9 on 2021-12-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0060_community_pending_self_moderation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='follow_request_backoff_new',
            field=models.DurationField(blank=True, help_text='Period during which a follow request will be automatically declined if the previous one was declined.', null=True),
        ),
    ]
