# Generated by Django 3.2.9 on 2021-12-15 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0062_transfer_follow_request_backoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='follow_request_backoff',
        ),
    ]
