# Generated by Django 3.2.9 on 2021-12-15 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0063_remove_community_follow_request_backoff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='follow_request_backoff_new',
            new_name='follow_request_backoff',
        ),
    ]
