# Generated by Django 3.2.11 on 2022-01-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0064_rename_follow_request_backoff_new_community_follow_request_backoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='members_friends_cache',
            field=models.DurationField(blank=True, help_text="Duration of cache for members' friends set", null=True),
        ),
    ]
