# Generated by Django 3.2.11 on 2022-01-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0078_filter_profile_update'),
        ('community', '0065_community_members_friends_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='twitter_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='moderation.socialuser'),
        ),
    ]
