# Generated by Django 3.2.13 on 2022-05-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0066_community_twitter_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccess',
            name='search_engine',
            field=models.BooleanField(default=False, help_text='Search engine.', verbose_name='Search engine'),
        ),
    ]
