# Generated by Django 3.2.15 on 2022-09-02 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_site_options'),
        ('community', '0067_apiaccess_search_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='sites.site'),
        ),
    ]
