# Generated by Django 3.2.16 on 2022-11-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0089_alter_mastodonuser_entity'),
        ('community', '0069_communitycategoryrelationship_follower_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='mastodon_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='community', to='moderation.mastodonuser'),
        ),
    ]
