# Generated by Django 3.2.16 on 2022-12-23 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0014_auto_20221223_0615'),
        ('community', '0070_community_mastodon_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='mastodon_access',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fediverse.mastodonaccess'),
        ),
    ]
