# Generated by Django 3.2.16 on 2022-12-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0072_reblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='require_following',
            field=models.BooleanField(default=True),
        ),
    ]
