# Generated by Django 3.2.16 on 2022-12-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0073_retweet_require_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retweet',
            old_name='require_following',
            new_name='require_friend',
        ),
        migrations.AddField(
            model_name='reblog',
            name='require_following',
            field=models.BooleanField(default=True),
        ),
    ]
