# Generated by Django 3.2.16 on 2022-12-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0074_auto_20221224_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reblog',
            name='moderation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reblog',
            name='require_follower',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reblog',
            name='require_following',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reblog',
            name='require_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='retweet',
            name='require_follower',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='retweet',
            name='require_friend',
            field=models.BooleanField(default=False),
        ),
    ]
