# Generated by Django 3.2.20 on 2023-08-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0097_alter_mastodonfollower_id_list'),
        ('community', '0075_auto_20221224_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_of_communities', to='moderation.Entity'),
        ),
    ]
