# Generated by Django 2.2.4 on 2019-09-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10, unique=True)),
                ('french', models.CharField(max_length=255)),
                ('english', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='mesh',
            index=models.Index(fields=['uid'], name='mesh_mesh_uid_f7a30f_idx'),
        ),
    ]
