# Generated by Django 2.2.4 on 2019-09-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesh',
            old_name='english',
            new_name='en',
        ),
        migrations.RenameField(
            model_name='mesh',
            old_name='french',
            new_name='fr',
        ),
    ]
