# Generated by Django 3.2.16 on 2022-12-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0005_mastodonscopes_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastodonscopes',
            options={'verbose_name_plural': 'Mastodon scopes'},
        ),
    ]
