# Generated by Django 3.2.16 on 2022-12-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0007_mastodonapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastodonapp',
            name='scopes',
            field=models.ManyToManyField(to='fediverse.MastodonScopes'),
        ),
    ]
