# Generated by Django 3.2.16 on 2022-12-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0009_mastodonaccess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastodonaccess',
            options={'verbose_name_plural': 'Mastodon accesses'},
        ),
    ]
