# Generated by Django 3.2.16 on 2022-12-23 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0057_tweetdj_conversatio_created_a2bbc2_idx'),
        ('moderation', '0094_auto_20221219_1414'),
        ('fediverse', '0012_alter_mastodonapp_redirect_uris'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri_id', models.BigIntegerField()),
                ('db_id', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField()),
                ('edited_at', models.DateTimeField(null=True)),
                ('in_reply_to_id', models.BigIntegerField()),
                ('in_reply_to_account_id', models.BigIntegerField()),
                ('status', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hashtag', models.ManyToManyField(blank=True, to='conversation.Hashtag')),
                ('reblogged_by', models.ManyToManyField(blank=True, related_name='reblogs', to='moderation.MastodonUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toots', to='moderation.mastodonuser')),
            ],
        ),
        migrations.AddIndex(
            model_name='toot',
            index=models.Index(fields=['in_reply_to_id'], name='fediverse_t_in_repl_e44baa_idx'),
        ),
        migrations.AddIndex(
            model_name='toot',
            index=models.Index(fields=['in_reply_to_account_id'], name='fediverse_t_in_repl_a6fce7_idx'),
        ),
    ]
