# Generated by Django 3.2.16 on 2022-12-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0013_auto_20221223_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toot',
            name='in_reply_to_account_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='toot',
            name='in_reply_to_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
