BBBBBBB BBBBBBBBBBB

BBBBB BBBBBBB
    BB BBBBBBBBB
        XXXXXXXXX XXXXX XXXX XXXXXXXX XXXX XXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
            XXXXXXX
                XXXX
                    XXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                XXXXX
                XXXX
                    XXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                XXXXX
                XXXX
                    XXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXXXXX XXXXXXX
                XXXXX
            XXXXXXXX
        XXXXXXX
    BBBB
        XXXXXXXXXXXX XXXXX XXXXXXXXXXX
        XXXXXX XXXXXXXX XXXXX XXXX XXX XXXXXXXX XXXXXXXX XXXXXXX XX XXX XXXXXXX XXXX XXXXX XXXXXX XXXXXXX X XXX XXXXXXXX XXXXXXXXXX
    BBBBB
BBBBBBBB
