# Generated by Django 2.2.1 on 2019-06-21 18:15

import blog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_blogpage_search_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='authors',
            field=models.ManyToManyField(default=blog.models.get_anonymous_user, to=settings.AUTH_USER_MODEL),
        ),
    ]
