# Generated by Django 2.2.1 on 2019-06-29 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messenger', '0007_auto_20190528_0341'),
        ('conversation', '0017_auto_20190621_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=15)),
                ('twitter_consumer_key', models.CharField(max_length=100)),
                ('twitter_consumer_secret', models.CharField(max_length=100)),
                ('twitter_access_token', models.CharField(max_length=100)),
                ('twitter_access_token_secret', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('hashtag', models.ManyToManyField(to='conversation.Hashtag')),
            ],
        ),
        migrations.CreateModel(
            name='Greet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Account')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.Campaign')),
            ],
        ),
    ]
