# Generated by Django 2.2.1 on 2019-06-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hashtag',
            field=models.ManyToManyField(blank=True, to='conversation.Hashtag'),
        ),
    ]
