# Generated by Django 2.2.4 on 2019-10-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_account_launch'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='backend_twitter_access_token',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='backend_twitter_access_token_secret',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='backend_twitter_consumer_key',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='backend_twitter_consumer_secret',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
