# Generated by Django 2.2.13 on 2020-06-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20200603_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='protected',
            field=models.BooleanField(default=False, help_text='Is this Twitter account protected (locked)?'),
        ),
    ]
