# Generated by Django 2.2.13 on 2020-11-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cookies',
            field=models.BinaryField(help_text='Session cookies for Selenium', null=True),
        ),
    ]
