# Generated by Django 2.2.13 on 2020-12-20 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_account_cookies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooky',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(choices=[('chrome', 'Chrome'), ('firefox', 'Firefox')], default='chrome', max_length=7)),
                ('binary', models.BinaryField(help_text='Session cookies for Selenium', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Account')),
            ],
        ),
    ]
