# Generated by Django 2.2.13 on 2020-12-20 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_cooky'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooky',
            options={'verbose_name_plural': 'Cookies'},
        ),
    ]
