# Generated by Django 2.2.13 on 2021-01-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20201220_0317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cooky',
        ),
    ]
