# Generated by Django 2.2.24 on 2021-10-19 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0067_auto_20211015_0726'),
        ('bot', '0012_delete_cooky'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='socialuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='moderation.SocialUser'),
        ),
    ]
