# Generated by Django 2.2.24 on 2021-10-26 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_account_socialuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='socialuser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='moderation.SocialUser'),
        ),
    ]
