# Generated by Django 3.2.15 on 2022-08-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20211103_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='twitter_access_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='twitter_access_token_secret',
        ),
        migrations.RemoveField(
            model_name='account',
            name='twitter_consumer_key',
        ),
        migrations.RemoveField(
            model_name='account',
            name='twitter_consumer_secret',
        ),
    ]
