# Generated by Django 3.2.15 on 2022-08-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20220825_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='backend_twitter_access_token',
            new_name='twitter_access_token',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='backend_twitter_access_token_secret',
            new_name='twitter_access_token_secret',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='backend_twitter_consumer_key',
            new_name='twitter_consumer_key',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='backend_twitter_consumer_secret',
            new_name='twitter_consumer_secret',
        ),
    ]
