# Generated by Django 3.2.15 on 2022-08-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_auto_20220825_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('consumer_key', models.CharField(blank=True, max_length=255)),
                ('consumer_secret', models.CharField(blank=True, max_length=255)),
                ('bearer_token', models.CharField(blank=True, max_length=255)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('redirect_uri', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterScopes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
