# Generated by Django 3.2.15 on 2022-08-27 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_auto_20220826_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth', models.CharField(choices=[('O1', 'OAuth 1.0a'), ('O2', 'OAuth 2.0')], default='O2', max_length=2)),
                ('token', models.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.account')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.twitterapp')),
            ],
        ),
    ]
