# Generated by Django 3.2.15 on 2022-09-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_account_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterapp',
            name='scopes',
            field=models.ManyToManyField(blank=True, to='bot.TwitterScopes'),
        ),
    ]
