# Generated by Django 2.0.13 on 2019-05-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20190525_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='categories',
            field=models.ManyToManyField(blank=True, to='moderation.Category'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='moderation.SocialUser'),
        ),
    ]
