# Generated by Django 2.0.13 on 2019-05-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20190525_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='receipts',
            field=models.ManyToManyField(blank=True, to='messenger.Receipt'),
        ),
        migrations.AlterField(
            model_name='campaignmessage',
            name='order',
            field=models.IntegerField(help_text='What order to display this person within the department.', unique=True, verbose_name='Ordre'),
        ),
    ]
