# Generated by Django 2.0.13 on 2019-05-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_auto_20190525_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='received',
        ),
        migrations.AddField(
            model_name='receipt',
            name='error',
            field=models.TextField(blank=True, help_text='Error message recorded if the message was not successfully sent.', null=True, verbose_name='Error message'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='event_id',
            field=models.BigIntegerField(blank=True, help_text='DM event id created if the message was successfully sent.', null=True, verbose_name='DM event id'),
        ),
    ]
