# Generated by Django 2.0.13 on 2019-05-26 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_auto_20190526_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='receipts',
        ),
        migrations.AddField(
            model_name='receipt',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign linked to this receipt.', null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.Campaign', verbose_name='Campaign'),
        ),
    ]
