# Generated by Django 2.0.13 on 2019-05-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_auto_20190526_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmessage',
            name='order',
            field=models.IntegerField(help_text='What order to display this person within the department.', verbose_name='Ordre'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignmessage',
            unique_together={('campaign', 'order')},
        ),
    ]
