# Generated by Django 2.2.17 on 2021-02-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0008_campaign'),
        ('messenger', '0007_auto_20190528_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='crowdfunding_campaign',
            field=models.ManyToManyField(blank=True, to='crowdfunding.Campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='restrict_by_category',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='restrict_by_crowdfunding',
            field=models.BooleanField(null=True),
        ),
    ]
