# Generated by Django 2.2.24 on 2021-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_campaign_backoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='event_id',
            field=models.BigIntegerField(blank=True, default=None, help_text='DM event id created if the message was successfully sent.', null=True, verbose_name='DM event id'),
        ),
    ]
