# Generated by Django 2.2.24 on 2021-09-18 11:55

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_auto_20210727_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='retweet_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, help_text='Min and/or max retweet(s) required to send msg. Bounds: [)', null=True),
        ),
    ]
