# Generated by Django 2.2.24 on 2021-09-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_campaign_retweet_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='restrict_by_category',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='restrict_by_crowdfunding',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
