# Generated by Django 3.2.9 on 2021-12-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_campaign_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
