# Generated by Django 3.2.9 on 2021-12-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0017_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
    ]
