# Generated by Django 3.2.9 on 2021-12-26 03:57

from django.db import migrations, models
import messenger.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0018_alter_status_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='content',
            field=models.TextField(default=None, validators=[messenger.models.validate_status]),
            preserve_default=False,
        ),
    ]
