# Generated by Django 3.2.9 on 2021-12-26 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0072_auto_20211105_1900'),
        ('messenger', '0019_alter_status_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusid', models.BigIntegerField(blank=True, default=None, help_text='Status id of the reply.', null=True, verbose_name='Status id')),
                ('error', models.TextField(help_text='Error message recorded if the status was not created.', verbose_name='Error message')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, help_text='Campaign linked to this log.', null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.campaign', verbose_name='Campaign')),
                ('status', models.ForeignKey(help_text='Status linked to this log.', on_delete=django.db.models.deletion.CASCADE, related_name='log', to='messenger.status', verbose_name='Tweet')),
                ('user', models.ForeignKey(help_text='Status is a reply to this user', on_delete=django.db.models.deletion.CASCADE, to='moderation.socialuser', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'StatusLog',
                'verbose_name_plural': 'StatusLogs',
            },
        ),
    ]
