# Generated by Django 3.2.9 on 2021-12-26 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0020_statuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='send_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='messenger.status'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status_delay',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
