# Generated by Django 3.2.12 on 2022-03-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0081_socialuser_language'),
        ('messenger', '0021_auto_20211226_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'Receipt', 'verbose_name_plural': 'Receipts'},
        ),
        migrations.AlterField(
            model_name='campaignmessage',
            name='order',
            field=models.IntegerField(help_text='What order to display this person within the department.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(help_text='Receipt for a message sent to this user', on_delete=django.db.models.deletion.CASCADE, to='moderation.socialuser', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='status',
            field=models.ForeignKey(help_text='Status linked to this log.', on_delete=django.db.models.deletion.CASCADE, related_name='log', to='messenger.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='user',
            field=models.ForeignKey(help_text='Status is a reply to this user', on_delete=django.db.models.deletion.CASCADE, to='moderation.socialuser', verbose_name='User'),
        ),
    ]
