# Generated by Django 3.2.12 on 2022-03-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0022_auto_20220317_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='restrict_by_last_investment',
            field=models.DurationField(blank=True, help_text='exclude if duration since last investment inferior to this value', null=True),
        ),
    ]
