# Generated by Django 3.2.12 on 2022-03-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0020_alter_projectinvestment_invoice'),
        ('messenger', '0023_campaign_restrict_by_last_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='crowdfunding_and',
            field=models.BooleanField(default=True, help_text='if multiple crowdfunding Campaigns: AND or OR?'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='crowdfunding_campaign',
            field=models.ManyToManyField(blank=True, help_text='deprecated in favor of crowdfunding m2m field with through model', to='crowdfunding.Campaign'),
        ),
    ]
