# Generated by Django 3.2.12 on 2022-04-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0020_alter_projectinvestment_invoice'),
        ('messenger', '0024_auto_20220329_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='crowdfunding_project',
            field=models.ManyToManyField(related_name='messenger_projects', to='crowdfunding.Project'),
        ),
    ]
