# Generated by Django 3.2.12 on 2022-04-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0020_alter_projectinvestment_invoice'),
        ('messenger', '0025_campaign_crowdfunding_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='crowdfunding_project',
            field=models.ManyToManyField(blank=True, related_name='messenger_projects', to='crowdfunding.Project'),
        ),
    ]
