# Generated by Django 3.2.16 on 2022-11-13 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0083_alter_human_socialuser'),
        ('messenger', '0027_receipt_error_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'Facture', 'verbose_name_plural': 'Receipts'},
        ),
        migrations.AlterField(
            model_name='campaignmessage',
            name='order',
            field=models.IntegerField(help_text='What order to display this person within the department.', verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(help_text='Receipt for a message sent to this user', on_delete=django.db.models.deletion.CASCADE, to='moderation.socialuser', verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='status',
            field=models.ForeignKey(help_text='Status linked to this log.', on_delete=django.db.models.deletion.CASCADE, related_name='log', to='messenger.status', verbose_name='Tweet'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='user',
            field=models.ForeignKey(help_text='Status is a reply to this user', on_delete=django.db.models.deletion.CASCADE, to='moderation.socialuser', verbose_name='Utilisateur'),
        ),
    ]
