# Generated by Django 2.0.8 on 2018-10-28 04:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treedj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusid', models.BigIntegerField(unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='conversation.Treedj')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tweetdj',
            fields=[
                ('statusid', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('userid', models.BigIntegerField()),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField()),
                ('reply', models.PositiveIntegerField()),
                ('like', models.PositiveIntegerField()),
                ('retweet', models.PositiveIntegerField()),
                ('parentid', models.BigIntegerField(null=True)),
            ],
        ),
    ]
