# Generated by Django 2.0 on 2018-10-12 15:45

from django.db import migrations
from django.apps import apps as global_apps

def import_data(apps, schema_editor):
    """
    Import the data of table Tweetdj & Tweetdj from test app mpttest into
    conversation tables.
    """
    try:
        OldTweetdj = apps.get_model('mpttest', 'Tweetdj')
        OldTreedj = apps.get_model('mpttest', 'Treedj')
    except LookupError:
        # The old app isn't installed anymore
        return
    
    NewTweetdj = apps.get_model('conversation', 'Tweetdj')
    NewTreedj = apps.get_model('conversation', 'Treedj')
    
    for o in OldTweetdj.objects.all():
        t = NewTweetdj(
            statusid = o.statusid,
            userid = o.userid,
            json = o.json,
            created_at = o.created_at,
            reply = o.reply,
            like = o.like,
            retweet = o.retweet,
            parentid = o.parentid)
        t.save()

class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]
    
    if global_apps.is_installed('mpttest'):
        dependencies.append(('mpttest', '0007_auto_20181004_2233'))

    operations = [
        migrations.RunPython(import_data, migrations.RunPython.noop),
    ]