# Generated by Django 2.0.8 on 2018-11-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetdj',
            options={'get_latest_by': '-statusid'},
        ),
    ]
