# Generated by Django 2.0.8 on 2018-11-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_auto_20181110_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdj',
            name='hashtag1',
            field=models.NullBooleanField(default=None, help_text='doctoctoc'),
        ),
        migrations.AddField(
            model_name='tweetdj',
            name='hashtag2',
            field=models.NullBooleanField(default=None, help_text='docstoctoc'),
        ),
        migrations.AddField(
            model_name='tweetdj',
            name='hashtag3',
            field=models.NullBooleanField(default=None, help_text='doctoctoctest'),
        ),
    ]
