# Generated by Django 2.0.8 on 2018-11-11 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_auto_20181110_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetdj',
            name='hashtag3',
        ),
    ]
