# Generated by Django 2.0.8 on 2018-11-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_remove_tweetdj_hashtag3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetdj',
            name='hashtag2',
        ),
        migrations.AddField(
            model_name='tweetdj',
            name='hashtag0',
            field=models.NullBooleanField(default=None, help_text='doctoctoc'),
        ),
        migrations.AlterField(
            model_name='tweetdj',
            name='hashtag1',
            field=models.NullBooleanField(default=None, help_text='docstoctoc'),
        ),
    ]
