# Generated by Django 2.0.8 on 2018-11-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0005_auto_20181111_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetdj',
            name='hashtag0',
            field=models.NullBooleanField(default=None, help_text='doctoctoc(test)'),
        ),
        migrations.AlterField(
            model_name='tweetdj',
            name='hashtag1',
            field=models.NullBooleanField(default=None, help_text='docstoctoc(test)'),
        ),
    ]
