# Generated by Django 2.0.13 on 2019-03-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0009_tweetdj_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetdj',
            name='retweetedstatus',
            field=models.NullBooleanField(default=None, help_text='Has retweeted_status'),
        ),
    ]
