# Generated by Django 2.0.13 on 2019-04-09 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0010_auto_20190302_0606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetdj',
            options={'get_latest_by': 'statusid'},
        ),
    ]
