# Generated by Django 2.2.1 on 2019-06-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0011_auto_20190409_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treedj',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='treedj',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='treedj',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
