# Generated by Django 2.2.1 on 2019-06-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0013_auto_20190603_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=101, unique=True)),
            ],
        ),
    ]
