# Generated by Django 2.2.1 on 2019-06-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0014_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdj',
            name='hashtag',
            field=models.ManyToManyField(to='conversation.Hashtag'),
        ),
    ]
