# Generated by Django 2.2.1 on 2019-06-18 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0020_donotretweet_moderator'),
        ('conversation', '0015_tweetdj_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdj',
            name='socialuser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.SocialUser'),
        ),
    ]
