# Generated by Django 2.2.1 on 2019-06-21 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0016_tweetdj_socialuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetdj',
            name='socialuser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tweets', to='moderation.SocialUser'),
        ),
    ]
