# Generated by Django 2.2.1 on 2019-07-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0017_auto_20190621_0234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetdj',
            options={'get_latest_by': 'statusid', 'ordering': ('-statusid',)},
        ),
    ]
