# Generated by Django 2.2.3 on 2019-08-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0018_auto_20190727_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treedj',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='treedj',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='treedj',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
