# Generated by Django 2.2.4 on 2019-10-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0019_auto_20190804_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetdj',
            name='hashtag0',
        ),
        migrations.RemoveField(
            model_name='tweetdj',
            name='hashtag1',
        ),
    ]
