# Generated by Django 2.2.4 on 2019-10-25 00:06

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('conversation', '0020_auto_20191007_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdj',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
