# Generated by Django 2.2.10 on 2020-02-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0023_auto_20200227_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetdj',
            name='hashtag',
            field=models.ManyToManyField(blank=True, to='conversation.Hashtag'),
        ),
    ]
