# Generated by Django 2.2.10 on 2020-03-09 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20191013_2322'),
        ('conversation', '0025_retweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.Account'),
            preserve_default=False,
        ),
    ]
