# Generated by Django 2.2.10 on 2020-03-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0027_auto_20200310_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweeted',
            name='retweet',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
