# Generated by Django 2.2.10 on 2020-03-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0039_auto_20200226_0322'),
        ('conversation', '0028_retweeted_retweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdj',
            name='retweeted_by',
            field=models.ManyToManyField(blank=True, to='moderation.SocialUser'),
        ),
    ]
