# Generated by Django 2.2.12 on 2020-06-03 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0029_tweetdj_retweeted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericbiginttaggeditem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_genericbiginttaggeditem_tagged_items', to='contenttypes.ContentType', verbose_name='content type'),
        ),
    ]
