# Generated by Django 2.2.13 on 2021-01-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0030_auto_20200603_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetdj',
            name='statusid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
