# Generated by Django 2.2.17 on 2021-01-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0032_twitterusertimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterusertimeline',
            name='last_api_call',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
