# Generated by Django 2.2.17 on 2021-01-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0033_twitterusertimeline_last_api_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterusertimeline',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='twitterusertimeline',
            name='statusid_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
