# Generated by Django 2.2.20 on 2021-04-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0034_auto_20210131_0718'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tweetdj',
            index=models.Index(fields=['userid'], name='userid_idx'),
        ),
    ]
