# Generated by Django 2.2.20 on 2021-04-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0035_auto_20210422_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetdj',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
