# Generated by Django 2.2.20 on 2021-04-29 19:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0036_auto_20210425_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetdj',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
