# Generated by Django 2.2.20 on 2021-04-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0038_auto_20210430_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetdj',
            name='quotedstatus',
            field=models.NullBooleanField(default=None, help_text='Has quoted_status', verbose_name='QT'),
        ),
    ]
