# Generated by Django 2.2.20 on 2021-05-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0039_auto_20210430_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterLanguageIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=35, unique=True)),
                ('language', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
