# Generated by Django 3.2.11 on 2022-01-22 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0078_filter_profile_update'),
        ('community', '0066_community_twitter_creator'),
        ('conversation', '0041_auto_20211103_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoNotRetweetStatus',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('identity', models.UUIDField()),
                ('version_start_date', models.DateTimeField()),
                ('version_end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('version_birth_date', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.community')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donotretweetstatus_moderations', to='moderation.socialuser', verbose_name='Moderator')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donotretweetstatus', to='conversation.tweetdj')),
            ],
        ),
        migrations.AddConstraint(
            model_name='donotretweetstatus',
            constraint=models.UniqueConstraint(fields=('id', 'identity'), name='versions_id_identity'),
        ),
        migrations.AddConstraint(
            model_name='donotretweetstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('version_end_date__isnull', True)), fields=('status', 'community'), name='current_status_community'),
        ),
    ]
