# Generated by Django 3.2.11 on 2022-01-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0042_auto_20220122_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='donotretweetstatus',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this do not retweet status record active?'),
        ),
    ]
