# Generated by Django 3.2.12 on 2022-02-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0045_alter_donotretweetstatus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostgresqlDictionaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfgname', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
