# Generated by Django 3.2.12 on 2022-02-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0046_postgresqldictionaries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postgresqldictionaries',
            options={'verbose_name_plural': 'Postgresql dictionaries'},
        ),
    ]
