# Generated by Django 3.2.12 on 2022-02-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0048_rename_postgresqldictionaries_postgresqldictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterlanguageidentifier',
            name='postgresql_dictionary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='conversation.postgresqldictionary'),
        ),
    ]
