# Generated by Django 3.2.12 on 2022-02-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0049_twitterlanguageidentifier_postgresql_dictionary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitterlanguageidentifier',
            options={'ordering': ['language']},
        ),
    ]
