# Generated by Django 3.2.12 on 2022-02-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0050_alter_twitterlanguageidentifier_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='twitterlanguageidentifier',
            unique_together={('tag', 'language')},
        ),
    ]
