# Generated by Django 3.2.12 on 2022-02-18 22:56

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0052_tweetdj_status_text'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tweetdj',
            index=django.contrib.postgres.indexes.GinIndex(fields=['status_text'], name='conversatio_status__e7dc97_gin'),
        ),
    ]
