# Generated by Django 3.2.12 on 2022-03-17 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0053_tweetdj_conversatio_status__e7dc97_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdj',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweetdj',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
