# Generated by Django 3.2.12 on 2022-03-20 00:08

from django.db import migrations

sql = """CREATE EXTENSION unaccent;
 CREATE TEXT SEARCH CONFIGURATION french_unaccent( COPY = french );
 ALTER TEXT SEARCH CONFIGURATION french_unaccent
 ALTER MAPPING FOR hword, hword_part, word
 WITH unaccent, french_stem;"""

reverse_sql = """DROP TEXT SEARCH CONFIGURATION french_unaccent;
 DROP EXTENSION unaccent;"""

class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0054_auto_20220317_1915'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]