# Generated by Django 3.2.13 on 2022-05-09 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_site_options'),
        ('hcp', '0008_auto_20211103_2157'),
        ('moderation', '0081_socialuser_language'),
        ('conversation', '0055_unaccent_french'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_parameters', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='moderation.Category')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_logs', to='sites.site')),
                ('taxonomies', models.ManyToManyField(to='hcp.Taxonomy')),
            ],
        ),
    ]
