# Generated by Django 3.2.13 on 2022-05-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0056_searchlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tweetdj',
            index=models.Index(fields=['-created_at'], name='conversatio_created_a2bbc2_idx'),
        ),
    ]
