# Generated by Django 2.0.6 on 2018-08-01 18:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpttest', '0002_auto_20180720_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('statusid', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('userid', models.BigIntegerField()),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('datetime', models.DateTimeField()),
                ('reply', models.PositiveIntegerField()),
                ('like', models.PositiveIntegerField()),
                ('retweet', models.PositiveIntegerField()),
            ],
        ),
    ]
