# Generated by Django 2.1 on 2018-08-07 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpttest', '0003_tweet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Statusdj',
        ),
        migrations.RenameModel(
            old_name='Tweet',
            new_name='Tweetdj',
        ),
    ]
