# Generated by Django 2.0 on 2018-10-04 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpttest', '0006_tweetdj_parentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetdj',
            name='datetime',
        ),
        migrations.AddField(
            model_name='tweetdj',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
