# Generated by Django 3.2.16 on 2022-11-13 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0084_entity'),
        ('users', '0002_auto_20211103_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='moderation.entity'),
        ),
    ]
