# Generated by Django 2.2.10 on 2020-05-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('grouping', models.CharField(max_length=255)),
                ('grouping_fr', models.CharField(max_length=255, null=True)),
                ('grouping_en', models.CharField(max_length=255, null=True)),
                ('classification', models.CharField(max_length=255)),
                ('classification_fr', models.CharField(max_length=255, null=True)),
                ('classification_en', models.CharField(max_length=255, null=True)),
                ('specialization', models.CharField(max_length=255)),
                ('specialization_fr', models.CharField(max_length=255, null=True)),
                ('specialization_en', models.CharField(max_length=255, null=True)),
                ('definition', models.TextField()),
                ('definition_fr', models.TextField(null=True)),
                ('definition_en', models.TextField(null=True)),
            ],
        ),
    ]
