# Generated by Django 2.2.10 on 2020-05-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0056_human'),
        ('hcp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCareProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.Human')),
            ],
        ),
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'ordering': ('grouping', 'classification', 'specialization'), 'verbose_name_plural': 'Taxonomy'},
        ),
        migrations.CreateModel(
            name='HealthCareProviderTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.Human')),
                ('healthcareprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcp.HealthCareProvider')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcp.Taxonomy')),
            ],
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='taxonomy',
            field=models.ManyToManyField(blank=True, through='hcp.HealthCareProviderTaxonomy', to='hcp.Taxonomy'),
        ),
    ]
