# Generated by Django 2.2.24 on 2021-07-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcp', '0002_auto_20200511_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcareprovider',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.Human', unique=True),
        ),
    ]
