# Generated by Django 2.2.24 on 2021-08-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcp', '0004_taxonomycategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomycategory',
            name='classification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='taxonomycategory',
            name='grouping',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='taxonomycategory',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
