# Generated by Django 2.2.24 on 2021-08-03 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0044_auto_20210415_0403'),
        ('hcp', '0005_auto_20210802_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomycategory',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='community.Community'),
            preserve_default=False,
        ),
    ]
