# Generated by Django 2.2.24 on 2021-08-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcp', '0006_taxonomycategory_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcareprovider',
            name='human',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moderation.Human'),
        ),
    ]
