# Generated by Django 2.2.24 on 2021-10-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcp', '0007_auto_20210811_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomedicalOccupationDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(null=True)),
                ('tag', models.CharField(max_length=36, unique=True)),
                ('summary', models.CharField(max_length=72)),
                ('description', models.TextField()),
                ('umls_cui', models.CharField(help_text='Unified Medical Language System: Concept Unique Identifier', max_length=8, unique=True)),
            ],
        ),
    ]
