# Generated by Django 3.2.16 on 2022-11-23 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0091_profile_json_index_gin'),
        ('hcp', '0008_auto_20211103_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprovider',
            name='entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='moderation.entity'),
        ),
    ]
