# Generated by Django 3.2.16 on 2022-11-25 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0091_profile_json_index_gin'),
        ('hcp', '0009_healthcareprovider_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprovidertaxonomy',
            name='creator_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.entity'),
        ),
    ]
