# Generated by Django 3.2.16 on 2022-11-25 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0091_profile_json_index_gin'),
        ('hcp', '0010_healthcareprovidertaxonomy_creator_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcareprovider',
            name='human',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.human'),
        ),
    ]
