# Generated by Django 2.0.13 on 2019-03-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
]

    operations = [
    migrations.RunSQL('''
        drop table if exists djstripe_customer cascade;
        delete from auth_permission where content_type_id in (select id from django_content_type where app_label = '{app_label}');
        delete from django_admin_log where content_type_id in (select id from django_content_type where app_label = '{app_label}');
        delete from django_content_type where app_label = '{app_label}';
        delete from django_migrations where app='{app_label}';
        '''.format(app_label='djstripe'))    
    ]
