# Generated by Django 2.2.24 on 2021-07-05 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('choice', '0003_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Is this Room actively used by the Participant?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice.Participant')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice.Room')),
            ],
            options={
                'unique_together': {('participant', 'room')},
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='room',
            field=models.ManyToManyField(through='choice.ParticipantRoom', to='choice.Room'),
        ),
        migrations.AddField(
            model_name='participant',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='choice.ParticipantType'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Django user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
