# Generated by Django 2.2.24 on 2021-07-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0005_auto_20210706_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('label', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
