# Generated by Django 2.2.24 on 2021-07-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0006_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(blank=True, help_text='context: diploma_slug , diploma_label, school_slug, school_tag', null=True),
        ),
    ]
