# Generated by Django 3.2.16 on 2022-11-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation', '0087_alter_human_socialuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastodonInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=8, unique=True)),
                ('socialuser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moderation.socialuser')),
            ],
            options={
                'unique_together': {('uid', 'socialuser')},
            },
        ),
    ]
