# Generated by Django 3.2.16 on 2022-11-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0088_mastodonuser'),
        ('mastodon', '0002_mastodoninvitation_autofollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastodoninvitation',
            name='socialuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='moderation.socialuser'),
        ),
    ]
