# Generated by Django 2.2.20 on 2021-04-17 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation', '0061_socialmedia_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAccessControl',
            fields=[
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='moderation.Category')),
                ('authorize', models.BooleanField(default=False)),
            ],
        ),
    ]
