# Generated by Django 2.2.20 on 2021-04-21 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0044_auto_20210415_0403'),
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAccessControl',
            fields=[
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='matrix', serialize=False, to='community.Community')),
                ('authorize', models.BooleanField(default=False)),
            ],
        ),
    ]
