# Generated by Django 2.2.24 on 2021-07-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0002_communityaccesscontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, help_text='temporary storage, erased after access_token creation', max_length=255, null=True)),
                ('homeserver', models.URLField()),
                ('nio_store', models.FileField(upload_to='nio_store/')),
            ],
        ),
    ]
