# Generated by Django 2.2.24 on 2021-07-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0004_remove_account_nio_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nio_store',
            field=models.CharField(blank=True, default='nio_store', max_length=255),
        ),
    ]
