# Generated by Django 2.2.24 on 2021-07-13 13:56

from django.db import migrations, models
import moderation.models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0061_socialmedia_emoji'),
        ('matrix', '0006_auto_20210710_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('friend_lower', models.PositiveIntegerField()),
                ('follower_lower', models.PositiveIntegerField()),
                ('follower_category', models.ManyToManyField(related_name='filtersocial_follower', to='moderation.Category')),
                ('friend_category', models.ManyToManyField(related_name='filtersocial_friend', to='moderation.Category')),
                ('social_media', models.ForeignKey(default=moderation.models.get_sentinel_social_media_id, on_delete=models.SET(moderation.models.get_sentinel_social_media), to='moderation.SocialMedia')),
            ],
        ),
    ]
