# Generated by Django 2.2.24 on 2021-07-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0007_filtersocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtersocial',
            name='follower_category',
            field=models.ManyToManyField(blank=True, related_name='filtersocial_follower', to='moderation.Category'),
        ),
        migrations.AlterField(
            model_name='filtersocial',
            name='friend_category',
            field=models.ManyToManyField(blank=True, related_name='filtersocial_friend', to='moderation.Category'),
        ),
    ]
