# Generated by Django 2.2.20 on 2021-05-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationservice',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationservice',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationservice',
            name='label_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationservice',
            name='label_fr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
