# Generated by Django 2.2.21 on 2021-05-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0002_auto_20210505_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetsubscription',
            name='service',
            field=models.ManyToManyField(blank=True, to='hive.NotificationService'),
        ),
        migrations.AlterField(
            model_name='tweetsubscription',
            name='broadcast_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweetsubscription',
            name='quote_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweetsubscription',
            name='retweet_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
