# Generated by Django 2.2.21 on 2021-05-09 00:06

from django.db import migrations, models
import hive.models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0003_auto_20210507_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetsubscription',
            name='age',
            field=models.DurationField(default=hive.models.default_age),
        ),
    ]
