# Generated by Django 2.2.21 on 2021-05-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0004_tweetsubscription_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationlog',
            name='log',
        ),
    ]
