# Generated by Django 2.2.21 on 2021-05-09 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0061_socialmedia_emoji'),
        ('hive', '0006_auto_20210509_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='socialuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='notificationlog', to='moderation.SocialUser'),
            preserve_default=False,
        ),
    ]
