# Generated by Django 2.2.24 on 2021-09-20 07:10

import django.core.validators
from django.db import migrations, models
import hive.models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0007_notificationlog_socialuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetsubscription',
            name='retweet_count',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(hive.models.retweet_count_min_value)]),
        ),
    ]
