# Generated by Django 2.2.3 on 2019-08-04 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.ManyToManyField(to='conversation.Tweetdj'),
        ),
        migrations.AlterField(
            model_name='link',
            name='website',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='link.Website'),
        ),
    ]
