# Generated by Django 2.2.3 on 2019-08-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_auto_20190804_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
