# Generated by Django 2.2.3 on 2019-08-05 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_auto_20190804_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='link.Website'),
        ),
    ]
