# Generated by Django 2.2.3 on 2019-08-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0021_auto_20190622_0217'),
        ('link', '0005_auto_20190805_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='socialuser',
            field=models.ManyToManyField(to='moderation.SocialUser'),
        ),
    ]
