# Generated by Django 2.2.3 on 2019-08-05 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_link_socialuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='link.Website'),
        ),
    ]
