# Generated by Django 2.2.4 on 2019-10-25 21:17

import community.models
from django.db import migrations, models
import django.db.models.deletion
import moderation.models
import versions.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation', '0036_auto_20191010_0109'),
        ('community', '0007_auto_20191022_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('identity', models.UUIDField()),
                ('version_start_date', models.DateTimeField()),
                ('version_end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('version_birth_date', models.DateTimeField()),
                ('uid', models.BigIntegerField()),
                ('community', models.ForeignKey(default=community.models.get_default_community, on_delete=django.db.models.deletion.CASCADE, related_name='tagging_queue', to='community.Community')),
                ('socialmedia', models.ForeignKey(default=moderation.models.get_default_socialmedia, on_delete=django.db.models.deletion.CASCADE, to='moderation.SocialMedia')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('identity', models.UUIDField()),
                ('version_start_date', models.DateTimeField()),
                ('version_end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('version_birth_date', models.DateTimeField()),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagging_process', to='moderation.SocialUser')),
                ('queue', versions.fields.VersionedForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagging.Queue')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=36, unique=True)),
                ('description', models.CharField(max_length=72)),
                ('community', models.ForeignKey(default=community.models.get_default_community, on_delete=django.db.models.deletion.CASCADE, related_name='tagging_category', to='community.Community')),
            ],
        ),
    ]
