# Generated by Django 2.2.4 on 2019-10-28 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0036_auto_20191010_0109'),
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': 'processes'},
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together={('queue', 'processor')},
        ),
    ]
