# Generated by Django 2.2.4 on 2019-10-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0002_auto_20191028_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='summary',
        ),
    ]
