# Generated by Django 2.2.4 on 2019-10-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0005_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
