# Generated by Django 2.2.4 on 2019-10-29 03:34

import django.core.validators
from django.db import migrations, models
import tagging.models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0006_auto_20191029_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(tagging.models.max_value)]),
        ),
    ]
