# Generated by Django 2.2.4 on 2019-10-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0008_auto_20191029_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='hashtag',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
