# Generated by Django 2.2.10 on 2020-03-05 03:31

import django.contrib.postgres.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('conversation', '0024_auto_20200227_2147'),
        ('tagging', '0009_auto_20191029_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='conversation.GenericBigIntTaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
