# Generated by Django 2.2.10 on 2020-03-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20191022_0037'),
        ('tagging', '0010_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='strings',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='community',
            field=models.ManyToManyField(blank=True, to='community.Community'),
        ),
    ]
