# Generated by Django 2.2.10 on 2020-03-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('conversation', '0024_auto_20200227_2147'),
        ('community', '0007_auto_20191022_0037'),
        ('tagging', '0011_auto_20200305_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagKeyword',
        ),
    ]
