# Generated by Django 2.2.13 on 2020-08-28 03:06

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('conversation', '0030_auto_20200603_0508'),
        ('tagging', '0012_auto_20200305_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='taggit',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='conversation.GenericBigIntTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
