# Generated by Django 2.2.13 on 2020-08-30 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0014_category_taggit_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='taggit',
        ),
    ]
