# Generated by Django 2.2.13 on 2020-08-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0015_remove_category_taggit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_category',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
