# Generated by Django 2.2.13 on 2020-09-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0017_tagkeyword_taggit_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagkeyword',
            name='tag',
        ),
    ]
