# Generated by Django 2.2.13 on 2020-09-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0018_remove_tagkeyword_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagkeyword',
            old_name='taggit_tag',
            new_name='tag',
        ),
    ]
