# Generated by Django 2.2.1 on 2019-07-07 16:33

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('crowdfunding', '0001_initial'), ('crowdfunding', '0002_auto_20190119_0118'), ('crowdfunding', '0003_auto_20190119_0211'), ('crowdfunding', '0004_auto_20190119_0214'), ('crowdfunding', '0005_auto_20190119_0234'), ('crowdfunding', '0006_project_transaction_count'), ('crowdfunding', '0007_auto_20190120_1827'), ('crowdfunding', '0008_auto_20190121_0056'), ('crowdfunding', '0009_auto_20190213_1809'), ('crowdfunding', '0010_auto_20190224_0514'), ('crowdfunding', '0012_auto_20190224_0523'), ('crowdfunding', '0013_tiers'), ('crowdfunding', '0014_auto_20190225_0624'), ('crowdfunding', '0015_auto_20190225_0629'), ('crowdfunding', '0016_auto_20190225_0631'), ('crowdfunding', '0017_auto_20190226_0334'), ('crowdfunding', '0018_auto_20190707_1733')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('goal', models.IntegerField(blank=True)),
                ('amount_paid', models.IntegerField(default=0)),
                ('investors', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('investor_count', models.IntegerField(default=0)),
                ('transaction_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=191)),
                ('emoji', models.CharField(blank=True, max_length=4)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('min', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('max', models.DecimalField(decimal_places=2, default=Decimal('Infinity'), max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.Project')),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'ordering': ['-max'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInvestment',
            fields=[
                ('pledged', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paid', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.Project')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=191)),
                ('public', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
