# Generated by Django 2.0.10 on 2019-01-19 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0002_auto_20190119_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pledged',
            new_name='paid',
        ),
    ]
