# Generated by Django 2.0.10 on 2019-01-19 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0003_auto_20190119_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='paid',
            new_name='amount_paid',
        ),
    ]
