# Generated by Django 2.2.4 on 2019-12-11 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_product'),
        ('crowdfunding', '0004_project_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Product'),
        ),
    ]
