# Generated by Django 2.0.10 on 2019-01-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0004_auto_20190119_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='investor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.IntegerField(blank=True),
        ),
    ]
