# Generated by Django 2.0.10 on 2019-01-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0005_auto_20190119_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
