# Generated by Django 2.2.9 on 2019-12-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0006_projectinvestment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvestment',
            name='invoice_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
