# Generated by Django 2.0.10 on 2019-01-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0007_auto_20190120_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvestor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='projectinvestor',
            name='name',
            field=models.CharField(blank=True, max_length=191),
        ),
    ]
