# Generated by Django 2.2.21 on 2021-06-18 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20190128_0414'),
        ('crowdfunding', '0009_projectinvestment_payment_intent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProcessorWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=255)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
