# Generated by Django 2.0.13 on 2019-02-24 04:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0010_auto_20190224_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvestment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
