# Generated by Django 3.2.9 on 2021-11-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0011_auto_20211103_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvestment',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crowdfunding.campaign'),
        ),
    ]
