# Generated by Django 2.0.13 on 2019-02-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0013_tiers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tiers',
            new_name='Tier',
        ),
    ]
