# Generated by Django 2.0.13 on 2019-02-25 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0014_auto_20190225_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tier',
            old_name='tag',
            new_name='title',
        ),
    ]
