# Generated by Django 2.0.13 on 2019-02-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0015_auto_20190225_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tier',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
