# Generated by Django 3.2.9 on 2021-12-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '__first__'),
        ('crowdfunding', '0013_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvestment',
            name='silver_invoice',
            field=models.ForeignKey(blank=True, help_text='ForeignKey to Invoice model of Silver billing app.', null=True, on_delete=django.db.models.deletion.PROTECT, to='silver.Invoice'),
        ),
    ]
