# Generated by Django 3.2.9 on 2021-12-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0019_projectinvestment_silver_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvestment',
            name='invoice',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Id of the invoice in the billing app.', null=True, unique=True, verbose_name='Invoice ID'),
        ),
    ]
