# Generated by Django 3.2.20 on 2023-07-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0020_alter_projectinvestment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvestment',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
