# Generated by Django 2.2.9 on 2020-01-20 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation', '0037_auto_20191101_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='moderation.Category')),
                ('authorize', models.BooleanField(default=False)),
            ],
        ),
    ]
