# Generated by Django 2.2.9 on 2020-01-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrol',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
