# Generated by Django 2.0.10 on 2019-01-28 03:14

from django.db import migrations

def insert_sites(apps, schema_editor):
    """Populate the sites model"""
    Site = apps.get_model('sites', 'Site')
    Site.objects.all().delete()

    # Register SITE_ID = 1
    Site.objects.create(domain='doctoctoc.net', name='DocTocToc.net')
    # Register SITE_ID = 2
    #Site.objects.create(domain='www.tourtodo.com', name='www')

class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_sites)
    ]
