# Generated by Django 3.2.9 on 2021-11-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20190128_0414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['domain'], 'verbose_name': 'site', 'verbose_name_plural': 'sites'},
        ),
    ]
