# Generated by Django 2.0.8 on 2018-12-23 21:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusid', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
