# Generated by Django 2.0.8 on 2018-12-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'get_latest_by': '-statusid', 'ordering': ['-statusid']},
        ),
    ]
