# Generated by Django 2.0.13 on 2019-02-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20181223_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'get_latest_by': '-statusid', 'ordering': ['-statusid'], 'verbose_name_plural': 'statuses'},
        ),
    ]
