# Generated by Django 2.2.4 on 2019-10-08 06:35

import community.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_status_community'),
        ('community', '0011_auto_20191006_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='community',
            field=models.ForeignKey(default=community.models.get_default_community, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
    ]
