# Generated by Django 3.2.9 on 2021-11-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_auto_20191010_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='json',
            field=models.JSONField(),
        ),
    ]
