# Generated by Django 2.0.8 on 2018-10-28 04:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('created_timestamp', models.BigIntegerField(help_text='Milliseconds since epoch')),
                ('sender_id', models.BigIntegerField()),
                ('recipient_id', models.BigIntegerField()),
                ('source_app_id', models.BigIntegerField(null=True)),
                ('text', models.TextField()),
                ('jsn', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ['-created_timestamp'],
                'get_latest_by': '-created_timestamp',
            },
        ),
    ]
