# Generated by Django 2.0 on 2018-10-05 04:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('label_en', models.CharField(max_length=255, unique=True)),
                ('label_fr', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('identity', models.UUIDField()),
                ('version_start_date', models.DateTimeField()),
                ('version_end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('version_birth_date', models.DateTimeField()),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('identity', models.UUIDField()),
                ('version_start_date', models.DateTimeField()),
                ('version_end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('version_birth_date', models.DateTimeField()),
                ('social_user', models.BigIntegerField(unique=True)),
                ('status', models.BigIntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
        migrations.CreateModel(
            name='UserCategoryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.Category')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated', to='moderation.SocialUser')),
                ('social_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='moderation.SocialUser')),
            ],
        ),
        migrations.AddField(
            model_name='socialuser',
            name='category',
            field=models.ManyToManyField(through='moderation.UserCategoryRelationship', to='moderation.Category'),
        ),
        migrations.AddField(
            model_name='socialuser',
            name='social_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='moderation.SocialMedia'),
        ),
        migrations.AddField(
            model_name='queue',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderation.SocialUser'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='moderation.SocialUser'),
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together={('id', 'identity')},
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('id', 'identity')},
        ),
    ]
