# Generated by Django 2.0.8 on 2018-10-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', 'data'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biggeravatar',
            field=models.ImageField(default='twitter/profile/images/bigger/default_profile_bigger.png', upload_to='twitter/profile/images/bigger'),
        ),
        migrations.AddField(
            model_name='profile',
            name='miniavatar',
            field=models.ImageField(default='twitter/profile/images/mini/default_profile_mini.png', upload_to='twitter/profile/images/mini'),
        ),
        migrations.AddField(
            model_name='profile',
            name='normalavatar',
            field=models.ImageField(default='twitter/profile/images/normal/default_profile_normal.png', upload_to='twitter/profile/images/normal'),
        ),
    ]
