# Generated by Django 2.0.13 on 2019-04-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_auto_20190403_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterlist',
            name='local_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
