# Generated by Django 2.0 on 2018-10-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_auto_20181007_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialuser',
            options={'ordering': ('user_id',), 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='queue',
            old_name='social_user',
            new_name='user_id',
        ),
    ]
