# Generated by Django 2.0.13 on 2019-04-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_twitterlist_local_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='label_en',
        ),
    ]
