# Generated by Django 2.0 on 2018-10-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_auto_20181013_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='socialuser',
            options={'ordering': ('user_id',)},
        ),
        migrations.AlterField(
            model_name='usercategoryrelationship',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='moderation.Category'),
        ),
    ]
