# Generated by Django 2.0 on 2018-10-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0006_auto_20181013_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='category',
            field=models.ManyToManyField(related_name='users', through='moderation.UserCategoryRelationship', to='moderation.Category'),
        ),
    ]
