# Generated by Django 2.0.13 on 2019-04-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0006_auto_20190404_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterlist',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
