# Generated by Django 2.0 on 2018-10-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0007_auto_20181013_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='category',
            field=models.ManyToManyField(through='moderation.UserCategoryRelationship', to='moderation.Category'),
        ),
    ]
