# Generated by Django 2.0.13 on 2019-04-08 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0007_auto_20190404_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='socialuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='moderation.SocialUser'),
        ),
    ]
