# Generated by Django 2.0 on 2018-10-15 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0008_auto_20181013_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategoryrelationship',
            name='datetimestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
