# Generated by Django 2.0 on 2018-10-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0009_usercategoryrelationship_datetimestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='status',
            new_name='status_id',
        ),
    ]
