# Generated by Django 2.0.13 on 2019-05-10 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0013_category_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('socialuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='moderation.SocialUser', verbose_name='socialuser')),
                ('active', models.BooleanField(default=False, help_text='Is this moderator active?')),
            ],
        ),
    ]
