# Generated by Django 2.0.13 on 2019-05-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('moderation', '0015_moderator_public'), ('moderation', '0016_image'), ('moderation', '0017_auto_20190520_0244'), ('moderation', '0018_remove_image_filerimagefield'), ('moderation', '0019_image_img'), ('moderation', '0020_auto_20190520_0421')]

    dependencies = [
        ('moderation', '0014_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='public',
            field=models.BooleanField(default=True, help_text='Does this moderator want to appear on the public list?'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='moderation/')),
            ],
        ),
    ]
