# Generated by Django 2.0.13 on 2019-05-30 19:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0017_auto_20190522_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterField(
            model_name='follower',
            name='followers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
