# Generated by Django 2.2.1 on 2019-06-07 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0018_auto_20190530_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donotretweet',
            name='duration',
        ),
        migrations.AddField(
            model_name='donotretweet',
            name='action',
            field=models.CharField(choices=[('W', 'Warn'), ('M', 'Moderate'), ('B', 'Ban')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='donotretweet',
            name='start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='donotretweet',
            name='stop',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
