# Generated by Django 2.2.1 on 2019-06-07 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0019_auto_20190607_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='donotretweet',
            name='moderator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='donotretweet_moderations', to='moderation.SocialUser', verbose_name='Moderator'),
        ),
    ]
