# Generated by Django 2.2.1 on 2019-06-22 00:17

from django.db import migrations, models
import django.db.models.deletion
import moderation.models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0020_donotretweet_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategoryrelationship',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated', to='moderation.SocialUser'),
        ),
    ]
