# Generated by Django 2.2.4 on 2019-09-05 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20190902_2359'),
        ('moderation', '0021_auto_20190622_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
    ]
