# Generated by Django 2.2.4 on 2019-09-09 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('moderation', '0022_queue_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
    ]
