# Generated by Django 2.2.4 on 2019-09-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0026_auto_20190915_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='quickreply',
        ),
        migrations.RemoveField(
            model_name='category',
            name='socialgraph',
        ),
    ]
