# Generated by Django 2.2.4 on 2019-09-26 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0001_initial'),
        ('moderation', '0027_auto_20190918_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='field',
            field=models.ForeignKey(help_text='Field as a MeSH heading', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_field', to='mesh.Mesh'),
        ),
        migrations.AddField(
            model_name='category',
            name='mesh',
            field=models.ForeignKey(help_text='Category as a MeSH heading', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='mesh.Mesh'),
        ),
    ]
