# Generated by Django 2.2.4 on 2019-09-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0028_auto_20190926_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='community',
        ),
    ]
