# Generated by Django 2.2.4 on 2019-09-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0029_remove_moderator_community'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
            "ALTER TABLE moderation_moderator DROP CONSTRAINT moderation_moderator_pkey;",
            "ALTER TABLE moderation_moderator ADD COLUMN id SERIAL PRIMARY KEY;"
            "ALTER TABLE moderation_moderator ALTER COLUMN socialuser_id DROP NOT NULL;"
            ],
            reverse_sql=[
            "ALTER TABLE moderation_moderator DROP CONSTRAINT moderation_moderator_pkey;",
            "ALTER TABLE moderation_moderator DROP COLUMN id",
            "ALTER TABLE moderation_moderator ALTER COLUMN socialuser_id SET NOT NULL;",
            "ALTER TABLE moderation_moderator ADD PRIMARY KEY (socialuser_id)",
            ],
            state_operations=[
            migrations.RemoveIndex(model_name='moderator', name='moderation_moderator_pkey'),
            migrations.AlterField(
                model_name='moderator', name='socialuser',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, null=True, blank=True, to='moderation.SocialUser',verbose_name='socialuser')
            ),
            migrations.AddField(
                model_name='moderator', name='id',
                field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ]
            )
    ]
