# Generated by Django 2.2.4 on 2019-09-27 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0031_auto_20190927_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='socialuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.SocialUser'),
        ),
    ]
