# Generated by Django 2.2.4 on 2019-09-28 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20190925_0421'),
        ('moderation', '0032_auto_20190927_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
    ]
