# Generated by Django 2.2.4 on 2019-09-28 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20190925_0421'),
        ('moderation', '0034_auto_20190928_0313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moderator',
            unique_together={('socialuser', 'community')},
        ),
    ]
