# Generated by Django 2.2.4 on 2019-10-09 23:09

import community.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0035_auto_20190928_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='community',
            field=models.ForeignKey(default=community.models.get_default_community, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='community',
            field=models.ForeignKey(default=community.models.get_default_community, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
        migrations.AlterField(
            model_name='twitterlist',
            name='community',
            field=models.ForeignKey(default=community.models.get_default_community, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
        migrations.AlterField(
            model_name='usercategoryrelationship',
            name='community',
            field=models.ForeignKey(default=community.models.get_default_community, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
    ]
