# Generated by Django 2.2.4 on 2019-11-01 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0036_auto_20191010_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='socialuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='moderation.SocialUser'),
        ),
    ]
