# Generated by Django 2.2.10 on 2020-02-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20191022_0037'),
        ('moderation', '0038_auto_20200224_0602'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercategoryrelationship',
            unique_together={('social_user', 'moderator', 'category', 'community')},
        ),
    ]
