# Generated by Django 2.2.10 on 2020-03-21 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0039_auto_20200226_0322'),
    ]

    operations = [
            migrations.RunSQL(
                'DROP INDEX IF EXISTS moderation_category_label_fr_1a19128c_like'
            )
    ]
