# Generated by Django 2.2.10 on 2020-03-22 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0042_auto_20200322_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategoryrelationship',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated', to='moderation.SocialUser'),
        ),
    ]
