# Generated by Django 2.2.10 on 2020-03-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0045_auto_20200323_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='label_en',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='label_fr',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categorymetadata',
            name='label',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='categorymetadata',
            name='label_en',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categorymetadata',
            name='label_fr',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
