# Generated by Django 2.2.10 on 2020-03-23 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0047_auto_20200323_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderation',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='moderation.CategoryMetadata'),
        ),
    ]
