# Generated by Django 2.2.10 on 2020-03-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0048_moderation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='senior',
            field=models.BooleanField(default=False, help_text='Is this moderator a seasoned moderator?'),
        ),
    ]
