# Generated by Django 2.2.10 on 2020-03-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0049_moderator_senior'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymetadata',
            name='dm',
            field=models.BooleanField(default=False, help_text='Add to DM Quick Reply list?'),
        ),
    ]
