# Generated by Django 2.2.10 on 2020-03-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0050_categorymetadata_dm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderation',
            options={'ordering': ['-version_start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='moderation',
            unique_together=set(),
        ),
    ]
