# Generated by Django 2.2.10 on 2020-03-28 01:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0051_auto_20200325_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followers',
            new_name='id_list',
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_list', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.SocialUser')),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
    ]
