# Generated by Django 2.2.10 on 2020-04-14 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0052_auto_20200328_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donotretweet',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donotretweet_moderations', to='moderation.SocialUser', verbose_name='Moderator'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
        migrations.AlterField(
            model_name='twitterlist',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
        migrations.AlterField(
            model_name='usercategoryrelationship',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
    ]
