# Generated by Django 2.2.10 on 2020-04-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0054_auto_20200415_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='type',
            field=models.CharField(choices=[('moderator', 'Moderator'), ('senior', 'Senior'), ('developer', 'Developer'), ('follower', 'Follower')], default='moderator', max_length=9),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
