# Generated by Django 2.2.10 on 2020-05-11 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0055_auto_20200419_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('djangouser', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('socialuser', models.ManyToManyField(blank=True, to='moderation.SocialUser')),
            ],
        ),
    ]
