# Generated by Django 2.2.13 on 2020-08-08 07:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0056_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
