# Generated by Django 2.2.13 on 2020-10-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0057_auto_20200808_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='public',
            field=models.BooleanField(default=False, help_text='Should this category be public (visible to users) or private (for internal use)?'),
        ),
    ]
