# Generated by Django 2.2.17 on 2021-02-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0060_socialuser_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='emoji',
            field=models.CharField(blank=True, help_text='emoji symbolizing a SocialMedia object for admin pages', max_length=255, null=True, unique=True),
        ),
    ]
