# Generated by Django 2.2.24 on 2021-09-05 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0062_auto_20210905_0416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['-version_start_date']},
        ),
    ]
