# Generated by Django 2.2.24 on 2021-09-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0063_auto_20210905_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymetadata',
            name='self_dm',
            field=models.BooleanField(default=False, help_text='Add to self Moderation DM Quick Reply list?'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='type',
            field=models.CharField(choices=[('moderator', 'Moderator'), ('senior', 'Senior'), ('developer', 'Developer'), ('follower', 'Follower'), ('self', 'Self')], default='moderator', max_length=9),
        ),
    ]
