# Generated by Django 2.2.24 on 2021-09-12 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optin', '0002_option_default_bool'),
        ('moderation', '0064_auto_20210911_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationOptIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('moderator', 'Moderator'), ('senior', 'Senior'), ('developer', 'Developer'), ('follower', 'Follower'), ('self', 'Self')], max_length=9)),
                ('authorize', models.BooleanField(default=None)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='optin.Option', verbose_name='OptIn option')),
            ],
        ),
    ]
