# Generated by Django 2.2.24 on 2021-09-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0065_moderationoptin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialuser',
            options={'get_latest_by': 'user_id', 'ordering': ('user_id',)},
        ),
    ]
