# Generated by Django 2.2.24 on 2021-10-15 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0050_auto_20211015_0726'),
        ('moderation', '0066_auto_20210918_1355'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moderator',
            unique_together={('socialuser', 'community')},
        ),
    ]
