# Generated by Django 2.2.24 on 2021-10-26 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0053_community_pending_moderation_period'),
        ('moderation', '0068_prospect'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prospect',
            unique_together={('socialuser', 'community')},
        ),
    ]
