# Generated by Django 2.2.24 on 2021-10-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0069_auto_20211026_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='socialuser',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
