# Generated by Django 3.2.9 on 2021-11-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0070_auto_20211027_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='twitterlist',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
