# Generated by Django 3.2.9 on 2021-11-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0071_auto_20211103_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='moderator',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
