# Generated by Django 3.2.9 on 2021-12-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0072_auto_20211105_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationoptin',
            name='type',
            field=models.CharField(choices=[('moderator', 'Moderator'), ('senior', 'Senior'), ('developer', 'Developer'), ('follower', 'Follower'), ('self', 'Self'), ('onhold', 'On hold')], max_length=9),
        ),
        migrations.AlterField(
            model_name='queue',
            name='type',
            field=models.CharField(choices=[('moderator', 'Moderator'), ('senior', 'Senior'), ('developer', 'Developer'), ('follower', 'Follower'), ('self', 'Self'), ('onhold', 'On hold')], default='onhold', max_length=9),
        ),
    ]
