# Generated by Django 3.2.11 on 2022-01-14 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0064_rename_follow_request_backoff_new_community_follow_request_backoff'),
        ('moderation', '0073_auto_20211230_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_protected', models.BooleanField(default=False, help_text='Require access to protected account?')),
                ('followers_count', models.PositiveSmallIntegerField(default=0, help_text='Minimum follower count required')),
                ('member_follower_count', models.PositiveSmallIntegerField(default=0, help_text='Minimum member follower count required')),
                ('statuses_count', models.PositiveSmallIntegerField(default=0, help_text='Minimum status count (retweet, reply, tweet) required')),
                ('profile_image', models.BooleanField(default=False, help_text='Require non default profile image?')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_filter', to='community.community')),
            ],
        ),
    ]
