# Generated by Django 3.2.11 on 2022-01-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0074_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this Filter active?'),
        ),
    ]
