# Generated by Django 3.2.11 on 2022-01-14 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0064_rename_follow_request_backoff_new_community_follow_request_backoff'),
        ('moderation', '0075_filter_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_filter', to='community.community'),
        ),
    ]
