# Generated by Django 3.2.11 on 2022-01-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0076_alter_filter_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='account_age',
            field=models.DurationField(blank=True, help_text='Required duration since account creation', null=True),
        ),
    ]
