# Generated by Django 3.2.11 on 2022-01-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0079_filter_member_follower_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='user_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
