# Generated by Django 3.2.13 on 2022-06-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0081_socialuser_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialuser',
            name='active',
        ),
    ]
