# Generated by Django 3.2.16 on 2022-11-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0082_remove_socialuser_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='socialuser',
            field=models.ManyToManyField(blank=True, related_name='human', to='moderation.SocialUser'),
        ),
    ]
