# Generated by Django 3.2.16 on 2022-11-13 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0084_entity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
    ]
