# Generated by Django 3.2.16 on 2022-11-13 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0085_alter_entity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='moderation.entity'),
        ),
    ]
