# Generated by Django 3.2.16 on 2022-11-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0086_socialuser_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='socialuser',
            field=models.ManyToManyField(blank=True, to='moderation.SocialUser'),
        ),
    ]
