# Generated by Django 3.2.16 on 2022-11-18 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0088_mastodonuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastodonuser',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='moderation.entity'),
        ),
    ]
