# Generated by Django 3.2.16 on 2022-11-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0089_alter_mastodonuser_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategoryrelationship',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this UserCategoryRelationship active?'),
        ),
    ]
