# Generated by Django 3.2.16 on 2022-11-21 00:32

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0090_usercategoryrelationship_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['json'], name='json_index_gin', opclasses=['jsonb_path_ops']),
        ),
    ]
