# Generated by Django 3.2.16 on 2022-11-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0092_linkedinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastodonuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mastodonuser',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
