# Generated by Django 3.2.16 on 2022-12-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0094_auto_20221219_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastodonuser',
            name='local_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
