# Generated by Django 3.2.16 on 2022-12-23 19:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0095_mastodonuser_local_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastodonfriend',
            name='id_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
