# Generated by Django 3.2.16 on 2022-12-29 02:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0096_alter_mastodonfriend_id_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastodonfollower',
            name='id_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
