# Generated by Django 2.2.9 on 2019-12-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0037_auto_20191101_0133'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='socialuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_queue', to='moderation.SocialUser'),
            preserve_default=False,
        ),
    ]
