# Generated by Django 2.2.10 on 2020-03-15 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_queue_socialuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Process',
        ),
    ]
