# Generated by Django 2.2.17 on 2021-02-02 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20200703_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('S', 'sent'), ('F', 'failed')], max_length=1, null=True)),
                ('dm_id', models.BigIntegerField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('queue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.Queue')),
            ],
        ),
    ]
