# Generated by Django 3.2.11 on 2022-01-25 17:34

from django.db import migrations, models
import django.db.models.deletion
import versions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0045_alter_donotretweetstatus_options'),
        ('request', '0007_alter_requestdm_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', versions.fields.VersionedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.queue', unique=True)),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='conversation.tweetdj')),
            ],
        ),
    ]
