# Generated by Django 3.2.11 on 2022-01-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_requeststatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requeststatus',
            options={'verbose_name_plural': 'Request statuses'},
        ),
    ]
