# Generated by Django 2.0.8 on 2018-12-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebTweet',
            fields=[
                ('statusid', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('conversationid', models.BigIntegerField()),
                ('userid', models.BigIntegerField()),
                ('username', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('time', models.PositiveIntegerField(help_text='time in seconds since epoch')),
                ('html', models.TextField()),
                ('text', models.TextField()),
                ('reply', models.PositiveIntegerField(null=True)),
                ('like', models.PositiveIntegerField(null=True)),
                ('retweet', models.PositiveIntegerField(null=True)),
                ('parentid', models.BigIntegerField(null=True)),
                ('rtl', models.BooleanField(help_text='right to left')),
                ('image0', models.URLField(null=True)),
                ('image1', models.URLField(null=True)),
                ('image2', models.URLField(null=True)),
                ('image3', models.URLField(null=True)),
                ('avatar_mini', models.URLField(null=True)),
                ('avatar_normal', models.URLField(null=True)),
                ('avatar_bigger', models.URLField(null=True)),
            ],
        ),
    ]
