# Generated by Django 2.0.8 on 2018-12-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtweet',
            name='avatar_bigger',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='webtweet',
            name='avatar_mini',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='webtweet',
            name='avatar_normal',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='webtweet',
            name='image0',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='webtweet',
            name='image1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='webtweet',
            name='image2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='webtweet',
            name='image3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
