# Generated by Django 2.0.9 on 2019-01-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20181218_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtweet',
            name='answer',
            field=models.PositiveIntegerField(help_text='anwsers by other accounts', null=True),
        ),
    ]
