# Generated by Django 2.2.1 on 2019-07-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_webtweet_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webtweet',
            old_name='username',
            new_name='screen_name',
        ),
    ]
