# Generated by Django 2.2.4 on 2019-12-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0002_auto_20190707_1834'),
        ('customer', '0005_provider_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='project',
            field=models.ManyToManyField(to='crowdfunding.Project'),
        ),
    ]
