# Generated by Django 2.2.4 on 2019-12-10 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_provider_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='copper_provider_id',
            new_name='copper_id',
        ),
    ]
