# Generated by Django 2.2.4 on 2019-12-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20191214_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
