# Generated by Django 3.2.17 on 2023-02-03 23:45

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20211103_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(default=customer.models.default_language, help_text='Language', max_length=35, verbose_name='Language'),
        ),
    ]
