# Generated by Django 2.2.24 on 2021-10-19 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0012_delete_cooky'),
        ('community', '0053_community_pending_moderation_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, help_text='Is this community still active in this network?')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_network', to='community.Community')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_community', to='network.Network')),
            ],
        ),
        migrations.AddField(
            model_name='network',
            name='community',
            field=models.ManyToManyField(through='network.NetworkCommunity', to='community.Community'),
        ),
        migrations.AddField(
            model_name='network',
            name='twitter_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network', to='bot.Account'),
        ),
    ]
