# Generated by Django 2.2.24 on 2021-10-20 05:42

import django.contrib.sites.managers
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_network_site'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='network',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
